### ISSUE TITLE
WP custom post types are not handled as Parse.ly sections

### ISSUE THREAD

**Issue by abelsonlive** [Parsely/wp-parsely#1004]
## Describe the bug

A person who uses custom post types in WordPress mentioned that they do not show up in Parse.ly.
For example, they have a Best Places type that they would expect to see as a section. Instead, it shows up under Uncategorized. 

## To Reproduce

You can open [this article](https://livability.com/best-places/2022-top-100-best-places-to-live-in-the-us/), view source, and then search for the parsely metadata block:
```
<script type="application/ld+json">
--
  | {"@context":"http:\/\/schema.org","@type":"NewsArticle","mainEntityOfPage":{"@type":"WebPage","@id":"http:\/\/livability.com\/best-places\/2022-top-100-best-places-to-live-in-the-us\/"},"headline":"Best Places to Live in the US in 2022","url":"http:\/\/livability.com\/best-places\/2022-top-100-best-places-to-live-in-the-us\/","thumbnailUrl":"https:\/\/livability.com\/wp-content\/uploads\/2022\/06\/2022Top100_landingpage_FINAL-150x150.jpg","image":{"@type":"ImageObject","url":"https:\/\/livability.com\/wp-content\/uploads\/2022\/06\/2022Top100_landingpage_FINAL-150x150.jpg"},"dateCreated":"2022-07-19T15:24:00Z","datePublished":"2022-07-19T15:24:00Z","dateModified":"2022-07-22T16:07:02Z","articleSection":"Uncategorized","author":[{"@type":"Person","name":"Livability.com"}],"creator":["Livability.com"],"publisher":{"@type":"Organization","name":"Livability","logo":"https:\/\/new.livability.com\/wp-content\/uploads\/2021\/03\/logo.svg"},"keywords":[]}
  | </script>
```

`articleSection` should be `Best Places` and not `Uncategorized`

**Comment by GaryJones** [comment]
Can you confirm if the customer has got the Best Places type selected as Track as Post in the plugin settings?

**Comment by acicovic** [comment]
@abelsonlive, did you get any feedback on this?

**Comment by abelsonlive** [comment]
@acicovic I believe this has been re-assigned. @Parsely/success  anyone on this ticket now?

**Comment by thompsonjoshua** [comment]
I reassigned that Support Ticket to myself following @abelsonlive's support rotation. However, that ticket auto-closed today due to customer inactivity over 15 business days.  Andy and I reached out three times but did not hear a response.

**Comment by acicovic** [comment]
OK, I'll close this issue as well then. We can reopen it if needed.
