### ISSUE TITLE
AMP support may need to be updated for AMP WP 1.x

### ISSUE THREAD

**Issue by davisshaver** [Parsely/wp-parsely#111]
I am working on an AMP native theme using AMP WP project and I noticed that the parsely JSON wasn't being printed on the page anymore. As a short term fix I applied the JSON using the AMP plugin's Analytics feature. Will cross file to AMP repo for visibility.

**Comment by joshuarrrr** [comment]
@davisshaver this issue was closed by #116, right?

**Comment by davisshaver** [comment]
Thanks @joshuarrrr!
