### ISSUE TITLE
Feature: track Custom Post Types by default

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1112]
## Is your feature request related to a problem?
wp-parsely tracks Posts and Pages, but does not track any Custom Post Types by default. This is to avoid tracking content that should not be tracked.
However, customers use Custom Post Types for their content and for non-post pages that are still important for them to update, track performance on, and enhance over time. This means that the plugin will not work as intended out of the box in those cases, and that it will need further configuration by the customer or us.

## Describe the solution you'd like
If a user has no settings, CPTs will be selected by default in the "Track as" option.  aka Track custom page types by default.
Customers can then adjust how they are tracked, or turn off tracking for page types depending on their needs. 
This prevents issues where customers think tracking is broken because they don't see data for some of their pages, which we see quite frequently.
Whether we handle a normal Post or Custom Post Type, we go though [this function](https://github.com/Parsely/wp-parsely/blob/747c7be772fbeac60e603af70aeb5584f2da84ad/src/Metadata/class-post-builder.php#L278-L309) which is called [here](https://github.com/Parsely/wp-parsely/blob/747c7be772fbeac60e603af70aeb5584f2da84ad/src/Metadata/class-post-builder.php#L168-L170).

**Comment by chriszarate** [comment]
It might be a useful middle ground to target only post types that support specific WordPress features, like the editor:

```php
get_post_types_by_support( [ 'editor' ] );
```

This would help narrow targeting to posts that are focused on content.

**Comment by danielabloch** [comment]
cloesd

**Comment by acicovic** [comment]
Another related idea that was voiced by @mjangda was to "track any public post type".

**Comment by mjangda** [comment]
We talked about doing some data collection to validate our approach.

**Comment by danielabloch** [comment]
@mjangda do we have new data to validate this approach? if not id suggest we remove this from the milestone until we do

**Comment by acicovic** [comment]
@danielabloch, we have some updates on this item and I'll be working on it.
