### ISSUE TITLE
Consistently use self::factory() in tests

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#1121]
## Describe the bug
The use of the non-static property of `$this->factory->...` in integration tests is deprecated. See https://core.trac.wordpress.org/changeset/54087. The use of the static method `self::factory()->...` is the correct approach.

While the patch includes a back-compat fix for populating `$this->factory`, it's set in the `WP_UnitTestCase_Base::set_up()`, so as of PHP 8.2 and WP trunk, any attempt to use `$this->factory->...` in test suite `set_up()` will fail as `factory` will be `null`.

This plugin doesn't seem to suffer from the `set_up()` issue, but it does have some `$this->factory->...` uses that should be switched over.

**Comment by acicovic** [comment]
Thanks for notifying us about this.
