### ISSUE TITLE
Don't alias '.../page' or '.../index' urls to homepage

### ISSUE THREAD

**Issue by jtotoole** [Parsely/wp-parsely#114]
See problem example here: https://www.thesun.co.uk/page/1392/

Metadata: 
```
{"@context":"http:\/\/schema.org","@type":"WebPage","headline":"The Sun","url":"https:\/\/www.thesun.co.uk"
````

`url` should be https://www.thesun.co.uk/page/1392/

Another offender: https://www.thesun.co.uk/index/s/page/8/

**Comment by joshuarrrr** [comment]
@jtotoole hm, this seems familiar as something we either fixed or tried to fix before.

**Comment by joshuarrrr** [comment]
ah, maybe not, although this covers similar ground: https://github.com/Parsely/wp-parsely/pull/107

**Comment by GaryJones** [comment]
The relevant conditionals for this URL are:

- `is_front_page()`
- `is_home()`
- `is_paged()`

As such, #152 may fix this, but it should be checked.

**Comment by mikeyarce** [comment]
Fixed in https://github.com/Parsely/wp-parsely/pull/152
