### ISSUE TITLE
Do not track post previews

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1155]
## Is your feature request related to a problem?
We have reports from Parse.ly support that some times the plugin injects tracking code within post previews. This should not be the case for drafts theoretically, but seems to be happening in practice.

Here are some parts of related communications, to highlight why this is important:

> A user creates a post, previews it while in Draft mode and that preview triggers a page view. Since the URL isn't live yet, we can't collect metadata, and that eventually creates some issues on our side.

> Customers will effectively experience a “duplicate” issue where there’s two versions of a piece surfaced in their dashboard--one without metadata (that showcases the earliest traffic) and one with metadata (sparked after a subsequent automated re-crawl).

> Even more importantly, a post often won't appear on the post list for some time when published. That's because in this scenario, we have a special schedule for recrawl attempts.

## Describe the solution you'd like
Unless there is a valid scenario for tracking post previews, make it so post previews never get tracked (even when their status is published).

**Comment by mehmoodak** [comment]
Looked into the code and seems like we are not adding tracker for drafted posts.

### Non Technical Answer:
- Create a published post, open devs tool and search `data-parsely-site` in html and here you will find the tracker script
- Create a draft post, search `data-parsely-site` and here you will not find the tracker script
  
Based on this we can say confidently that the plugin don't tracks drafted posts.

### Technical Answer:
- We enqueue `wp-parsely-tracker` script in code inside `enqueue_js_tracker`
- Here we have bunch of checks to avoid loading the script for particular cases.
- In these checks we have [a check](https://github.com/Parsely/wp-parsely/blob/develop/src/class-scripts.php#L85) that includes `! Parsely::post_has_trackable_status( $post )` condition, inside this function we make sure to only return true for the posts with status `publish` ([code](https://github.com/Parsely/wp-parsely/blob/develop/src/class-parsely.php#L224-L225))

But we do track post previews for the published post, will open the PR to fix this issue as also recommended in the solution above.
