### ISSUE TITLE
Content Helper is being blocked by certain ad blockers

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1203]
## Is your feature request related to a problem?
The Content Helper is being blocked by certain ad blockers (I've seen uBlock Origin doing that, but there may be others).

This is unwanted since:
1. No actual tracking takes place in the Content Helper.
2. The block cripples our functionality and displays an "Error: You are probably offline" message, which is totally uninformative/misleading.

## Describe the solution you'd like
1. Test with 2-3 popular ad blockers to see which of those exhibit the blocking behavior.
2. Investigate what triggers the block, and if there are any reasonable ways to work around it.
3. When the "Error: You are probably offline" message occurs, include some text where we explain that certain ad blockers can cause this, so users are aware. If everything else fails, this will at least give some information to our users so they can mitigate the issue.

**Comment by mehmoodak** [comment]
Based on initial findings I am able to repro this issue while using:

- uBlock on Firefox (privacy badger and firefox builtin blockers doesn't block the request)
- Brave with option Aggressively block trackers and ads (no extension)

Seems like this issue is happening due to the presence of `analytics` keyword in our url path because replacing it with something else like `stats` doesn't block the request which means maybe we can avoid this issue by changing our url path.

**Example:**
This request is blocked by uBlock and Brave both

```
fetch( 'https://SITE_URL/wp-json/wp-parsely/v1/analytics/posts?limit=5&section=Uncategorized&_locale=user' )
	.then( ( res ) => {
		console.log( res );
	} );
```

Just after replacing `analytics` with `stats` doesn't block the request

```
fetch( 'https://SITE_URL/wp-json/wp-parsely/v1/stats/posts?limit=5&section=Uncategorized&_locale=user' )
	.then( ( res ) => {
		console.log( res );
	} );
```

**Comment by acicovic** [comment]
Great detective work! 😃

I think that it's worth making the switch from `analytics` to something like `stats`, so we should decide on the keyword to be used.

Before that and as a first step, I would suggest working on the error message, since we might always hit an edge case, or things might suddenly change (for example, more ad blockers start blocking URLs with whatever keyword we choose).

The error message might appear in any Content Helper panel (and in the future in other places, like the WP dashboard for example), so it has a wide scope which is beyond Gutenberg. We could create something like an "Error Message Hint" mechanism that would give a hint based on the error message being returned (because we do want to keep the original WP Rest API error message as well).

So if we get the error:
> Error: You are probably offline

We could have an output like:
> Error: You are probably offline
> **Hint**: This error can be sometimes caused by ad-blockers or browser tracking protection. Please whitelist this website where needed and try again.

This mechanism would allow us to give user-friendlier hints for various weird error messages. For example, in the internet outages I got a few days ago, another error message was displaying that was not clear about the potential reason.

This is open to discussion and if there are any better ideas, they are welcome. Also copying here @chriszarate and @danielabloch for awareness. This is a high-priority issue, since it renders the Content Helper unusable.
