### ISSUE TITLE
Update endpoint comments from `mixed` to `stdClass`?

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1209]
Line 47 treats the items of the `$response` array as `stdClass` - is that right? If so, could `stdClass` be used here instead of `mixed`?

_Originally posted by @GaryJones in https://github.com/Parsely/wp-parsely/pull/1093#discussion_r1025238265_

**Comment by mehmoodak** [comment]
Will get fixed in #1252
