### ISSUE TITLE
Include Parse.ly data on the Posts page

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1215]
## Is your feature request related to a problem?
One of the most important pages visited by content creators in a CMS is the Posts page. This is where they see all the posts being published, edited, etc. 

By adding a column to the Posts section/page in VIP/wp-admin, we can provide quick context on published posts from the primary area in the CMS where creators review, search for, sort, and create posts.

## Describe the solution you'd like
As a content creator, I want to see how content on the site has been performing so I can make better decisions about what to write about, what articles to revisit and improve, and what to deprioritize in our editorial strategy. I want to see this on the main page that I access to look at all posts on my site. 

**Screen options**
Add a column option called Parse.ly Content Helper. When the column is selected and applied to the page, the below metrics will display in the table view of posts. 

**Parse.ly metrics to include in the column**
<img width="544" alt="Screenshot 2022-11-29 at 5 21 17 PM" src="https://user-images.githubusercontent.com/88679146/204661182-4828fb0f-a695-486d-b573-3ed445a74d5b.png">

- page views
- visitors
- avg. time

**Comment by acicovic** [comment]
Thank you for the screenshot, it is very helpful to have this visual representation.

From the API/data perspective, we already get that data in the Post Editor so we should be fine.

I think that the follow-up questions are of the sort:
- How many columns should actually this be? Should we try to actually limit this to 1, or 2 are fine?
- Does this need a proper design session with @garrettvercoe?

If we ever need to display more data, having too many columns could be problematic. In this case an idea would be to see if it is possible to show additional data when clicking the value (taking into account any accessibility concerns and implement this for everyone). 

Copying @chriszarate @mehmoodak and @GaryJones for awareness.

**Comment by danielabloch** [comment]
1. I don't know how many columns it should be. A goal here is for us to add some Parse.ly design/style to the filter that shows Parse.ly data, so it might be these 2, it might need to be 3 (i.e. I don't know if we can show two metrics in one column called Context). 
2. That is why I'd like a design session with Garrett. However, this is a light touch session, to get his keen eye on our idea and check it for style and consistency with the core product. 

Agree that more than these columns is a problem; this page is already congested with columns.

**Comment by acicovic** [comment]
Note for anyone who starts working on this:

The final guideline is to take the 3 described metrics (page views, visitors, avg. time) and put them under a single column.

**Comment by acicovic** [comment]
Also logging this idea here so it does not get forgotten:

If we turn the column contents into a link for doing something, we could append a querystring to it, which would allow the target page to know that the request is coming from the plugin, and have some special behavior or process for it.

This is a general idea, and we do not have yet determined a specific course of action for it.

**Comment by danielabloch** [comment]
Decisions from our Dec. 15 call
- No filters. 
- Time period is 7 days, like the Content Helper

Questions to answer
- How big is the lift / estimate for sorting? If trivial, include it. If not, don’t work on it.
- How to make the smallest number of API calls with external api? Max posts you can display on this page is 500, default is 20.

**Comment by danielabloch** [comment]
Per 1/4 we decided to move forward with this ticket **without** sorting capabilities on the metrics column. We'll review this functionality in a subsequent ticket.
