### ISSUE TITLE
Update React to version 18

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1265]
## Is your feature request related to a problem?
Many of the WordPress packages that we use as dependencies are switching to React 18 and we already cannot merge the respective dependabot PRs due to version conflicts. I assume that the situation will only get intensified as time goes by. Yesterday we had 2 PRs like that, today we have 3.

## Describe the solution you'd like
Update to React 18.

## Additional context
Related/similar to #1796.

**Comment by mehmoodak** [comment]
As of now the latest version of WordPress is `6.1` and the Gutenberg editor shipped in that is using React version `17.0.2` ([src](https://github.com/WordPress/gutenberg/blob/wp/6.1/package.json#L215)) so should we still upgrade it or wait until React dependency gets updated in Gutenberg version which is shipped with WordPress.

I think we should wait.

**Comment by acicovic** [comment]
If you think that we should better wait, let's do that.

Even when we upgrade, we should still be compatible with older WP versions. Do you foresee a problem with that?

**Comment by acicovic** [comment]
Currently our plugin supports WP 5.0 or greater.

**Comment by mehmoodak** [comment]
> Even when we upgrade, we should still be compatible with older WP versions. Do you foresee a problem with that?

Yes if we start using some functionality which is provided by React v18 then it can cause a breaking change for older versions of WordPress e.g. if we use [createRoot](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis) provided by React v18.

Another approach is we upgrade our plugin to v18 but don't use these new features which I think we should avoid as while writing code it will not give errors on features which aren't going to work in reality on WordPress. Thoughts?

**Comment by acicovic** [comment]
If upgrading to v18 without changing code syntax and not using new features is an option, I would consider it. I also wonder if we can have some sort of linter that can check for React newer syntax/features and warn us about it when we use them unintentionally.

In a different scenario, I don't know how much time we would need to wait, and whether we will start having issues with our dependencies that are going forward. So I'd be in favor of planning this as needed in order to avoid any possible unwanted surprises.

**Comment by acicovic** [comment]
WordPress 6.2 is out with React 18. Does this change the status of this issue?

**Comment by mehmoodak** [comment]
> WordPress 6.2 is out with React 18. Does this change the status of this issue?

We should be able to do the upgrade now ...... but I think we should still avoid using new features so that our plugin will work for older versions of WordPress.

**Comment by acicovic** [comment]
> We should be able to do the upgrade now ...... but I think we should still avoid using new features so that our plugin will work for older versions of WordPress.

I totally agree.

**Comment by acicovic** [comment]
Looking [here](https://core.trac.wordpress.org/browser/tags/5.0/package.json), I see that we should go with the react 16.6.3 feature set as the requirement.

**Comment by acicovic** [comment]
This should be fixed in #1847.
