### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by joshuarrrr** [Parsely/wp-parsely#134]
We're not using it heavily, so it should be fairly straightforward to replace jQuery calls with vanilla JS.

**Comment by jase-d-ace** [comment]
does it need to be removed from anywhere besides [here](https://github.com/Parsely/wp-parsely/blob/9fb6245ae7e0ba6bde41df892faa55958e48ab1b/parsely-javascript.php#L28)?

**Comment by joshuarrrr** [comment]
Yeah, `jQuery.find()` is also used: https://github.com/Parsely/wp-parsely/search?q=jQuery&unscoped_q=jQuery

**Comment by jblz** [comment]
#236 got us a lot of the way there, but the recommended widget still relies on jQuery:

https://github.com/Parsely/wp-parsely/blob/3cca62a4c228af6bd8893e744e710fb6b4269e94/src/class-parsely-recommended-widget.php#L95-L116

**Comment by pauarge** [comment]
jQuery has been removed
