### ISSUE TITLE
Add nonce support to the Content Helper and our WP Rest Endpoints

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1340]
## Is your feature request related to a problem?
We currently do not have a nonce implementation for our Content Helper and WP Rest Endpoints.

## Describe the solution you'd like
Research and implement a nonce solution for the Content Helper and WP Rest Endpoints.

**Comment by acicovic** [comment]
Some context from #667:

> About nonces, if the endpoint could be called by an external bad actor (?), then this could be a good idea. Having said that, in almost every case the attacker would need to know the API secret. As far as I'm aware, the only endpoint that works without it is /related which is used for the Recommendations Block and there wouldn't be any sensitive data there. We could consider implementing this though as an extra security feature, just to be even safer.

**Comment by acicovic** [comment]
@mehmoodak, am I correct that this is not needed with the new implementation? If yes, let's close this.

**Comment by mehmoodak** [comment]
Yes not needed. Closing the issue.
