### ISSUE TITLE
Content Helper: Consider removing or improving fetch retries

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1341]
## Is your feature request related to a problem?
Within parts of the Content Helper's code, we have this where the Parse.ly API gets called:
```ts
const FETCH_RETRIES = 3 // Number of attempts to fetch the data before displaying an error.

function MyComponent() {
	useEffect( () => {
		const fetchData = async ( retries: number ) => {
			provider.getData()
				.then( ( result ) => {
					// Populate component with data.
				} )
				.catch( async ( err ) => {
					if ( retries > 0 ) {
						await new Promise( ( r ) => setTimeout( r, 500 ) );
						await fetchPosts( retries - 1 );
					} else {
						// Show the error
					}
				} );
		};

		setLoading( true );
		fetchPosts( FETCH_RETRIES );
	}, [] );
}
```
This means that if the initial fetch of the data fails, we attempt to fetch it up to two times more, and display the error if all attempts failed. This seems like a good idea but it actually results in extra API calls, that could be a significant amount at scale and with many users.

This retry mechanism has been firing a lot when it shouldn't, for example when we have wrong credentials. There are many valid scenarios where we should get an error and stop there, but this code just keeps on firing, and another side effect of this is that errors appear with an increased latency, since this code has resulted in 3 calls instead of 1.

I can propose two solutions:
1. Get rid of this logic. Having it so far, I do not think we got any real advantages out of it.
2. Flag the errors that should not be retried, as to only retry for errors that are perceived as "unknown/unexpected".

## Describe the solution you'd like
I'm opening this for discussion to see if an action should be taken, and which of the 2 approaches is preferred. Tagging @mehmoodak, @mjangda and @chriszarate for thoughts and discussion.

I'd just remove it if there are no strong advantages in keeping it (which I think is the case).

**Comment by mehmoodak** [comment]
As of now I think going with Solution 1 is fine because as you already mentioned this is not giving any real advantage.

If needed we can implement it back in future.

**Comment by mjangda** [comment]
On retries, I think there's benefit to having a single retry to account for network issues or unexpected issues (i.e. go from 3 => 1). In majority of the cases this shouldn't kick in anyway.

However, we should be smarter and more defensive about the API failure response. For example, if the Parsely API is down, we should catch that and stop making calls, even if it's for a short time period. To do this, we can have a counter via transients that tracks failures and after a certain threshold, we set an option which blocks API calls for 5 minutes.

For the wrong credentials use case, I think we should do the following:

- Validate the credentials on save (there's no specific endpoint for this but can just make a call to one of the protected ones where we expect data to be returned) and set an option if the request fails. That option should completely block future API calls until the validation completes successfully. It should also show an error on the Settings screen with details on what to do next.
- If credentials are valid on save but we get bad credential responses from future API calls (i.e. 403), we should set the option to completely block API requests.

**Comment by acicovic** [comment]
I just merged https://github.com/Parsely/wp-parsely/pull/1541 and I'll be marking this issue as resolved. If we think further enhancements are needed here, we can work further on this in a future iteration.
