### ISSUE TITLE
Content Helper: Allow user to select time period filter(s)

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1352]
### Is your feature request related to a problem?
Different customers care about different time periods of data (1 day, 7 days, 30 days, etc.). By providing customers with filtering options, we let them see the time frame that is most relevant to them while editing or authoring content in their CMS.

### Describe the solution you'd like
Ability for customers to select 1 of several time period options with which to evaluate their content performance.

Time period filtering option ideas

- Last 24 hours
- Right now (real-time)
- Last 7 days
- Last 30 days

Available on

- Performance Details
- Top Related Posts
- Dashboard Widget

### Describe alternatives you've considered
Creating a default time period that customers cannot edit. We launched this in 3.6. 

### Notes

**Comment by danielabloch** [comment]
We currently offer last 7 days by default.

I recommend we prioritize additional time filters in the following order:
1. Real time: "Real-time data includes the last 24 hours and updates every five seconds. It can be seen throughout the dashboard." ([source](https://docs.parse.ly/does-parse-ly-show-realtime-data/#:~:text=Parse.ly%20provides%20both%20real,to%20the%20Parse.ly%20dashboard.))
2. Last 30 days -- stretch goal only, not a requirement

**Comment by acicovic** [comment]
Waiting for feedback on real-time due to caching issues, this is done for:
- [x] Dashboard Widget
- [x] Performance Details pane (PCH Sidebar)
- [x] Top Related Posts pane (PCH Sidebar)

**Comment by acicovic** [comment]
Closing this issue as implemented per the work done in #1876 and #1898. Real-time is still blocked due to caching issues, but it's under our radar and in internal discussion. If the caching issue gets fixed, we already have the code to implement it.
