### ISSUE TITLE
PCH: show related links already included in the post

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1353]
## Is your feature request related to a problem?
When a customer is preparing a new post or updating an existing post, one of the steps pre-publish is making sure relevant links to other articles are included in the post. By showing customers which of the related top-performing posts has been included in the post already, they can quickly see how much relevant content has been added to the post, and where there are gaps/opportunities to add more posts. 

## Describe the solution you'd like
As a content creator, I want you to show me top related posts and which ones I have already included in the post I am editing or creating. That way, I know what else I can or should add, and know which posts I have already added.

## Describe alternatives you've considered
Providing customers with top related posts and letting them decide what to include or not. This was covered with wp-parsely 3.6 launch of top-performing related posts. 

## Additional context
Visual aid to identify what's included / what's not. 
<img width="344" alt="checkmarks" src="https://user-images.githubusercontent.com/88679146/216222094-a9903f00-39b0-4654-9f03-786883fcf20a.png">

**Comment by acicovic** [comment]
This was shipped as a bonus in 3.14.0 thanks to @vaurdan's work. Marking this issue closed.
