### ISSUE TITLE
[bug] PCH referral distribution only shows direct traffic

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1367]
## Describe the bug
The referrer section of Performance Details only shows direct traffic, even when there are other referrers. 

## To Reproduce
1. Go to (https://docs.parse.ly/wp-admin/post.php?post=5378&action=edit)
2. Click on PCH sidebar
3. Scroll down to Performance Details
4. See error --> The PCH says it's all direct
5. View in Parse.ly
6. View in Parse.ly - change filter to last 7 days (Jan 29 - Feb 2)
7. If you look at the past 7 days in parse.ly, there are actually a few search referrals

## Expected behavior
The referrals performance details shows you all referrer channels. 

## Screenshots
PCH: Distribution for last 7 days (Jan 29 - today): 41 page views from Direct
<img width="1041" alt="Screenshot 2023-02-03 at 1 27 48 PM" src="https://user-images.githubusercontent.com/88679146/216679620-497d010b-665b-45d9-8e63-d131854e9c7b.png">

View in Parse.ly takes me to Pulse view for today, not last 7 days (new bug)

Change time period to Jan 29 - today) in Parse.ly: 33 page views from Direct
The distribution we'd want to see on the post
<img width="1040" alt="Screenshot 2023-02-03 at 1 31 40 PM" src="https://user-images.githubusercontent.com/88679146/216680226-f0b72bd8-ab6c-48d7-a294-37c60e124531.png">

## Environment
Chrome browser
Active Parse.ly plugin

**Comment by acicovic** [comment]
I can confirm this.

On my local environment:

![image](https://user-images.githubusercontent.com/23142906/217805759-ce23fb07-8720-413c-8de1-68346323296e.png)

On the remote site:

![image](https://user-images.githubusercontent.com/23142906/217805604-9a043880-a11d-4fb7-8273-5595b3338776.png)

Style is broken too, but this sees to be site-specific (and is another issue).

@mehmoodak: I think we should add this one to 3.7, what do you think?

**Comment by mehmoodak** [comment]
> Style is broken too, but this sees to be site-specific (and is another issue).

Yes it is a site specific issue.

> I think we should add this one to 3.7, what do you think?

This issue has been already fixed in https://github.com/Parsely/wp-parsely/issues/1377 and will be a part of `3.6.2` and `3.7` releases.

**Comment by mehmoodak** [comment]
The above PR does fix the errors that we are facing but seems like there is also some functional difference between plugin and Parse.ly so re-opening the issue.
