### ISSUE TITLE
Content Helper Dashboard Widget: Images can be blocked by ad blockers

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1453]
## Is your feature request related to a problem?
I noticed that certain ad blockers might be blocking the thumbnail images in the Content Helper Dashboard Widget, as the URL they originate from contains the `parsely.com` string.

## Describe the solution you'd like
Create a WP REST API endpoint that serves the images, or find an alternative solution that works.

**Comment by mjangda** [comment]
I guess this mostly impacts editorial users? My thought is that it's probably not a huge problem.

If we really want to solve it, I think a better approach (instead of proxying through the REST API) would be to either fallback to or directly use the Jetpack Photon API for the images.

**Comment by acicovic** [comment]
This is a visual glitch, but it doesn't have any impact besides that. It does not hinder any functionality.

There are a different number of workarounds that can be employed here, but I haven't decided which way to go with this yet.
