### ISSUE TITLE
Content Helper/Recommendations Block: Add an appropriate itm_source to URLs

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1473]
## Is your feature request related to a problem?
The URLs we're getting from the Parse.ly API have an `itm_source` value of `parsely-api`. However, when those and other URLs are used from within the Content Helper or the Recommendations Block, we want to have an appropriate `itm_source` value for them.

## Describe the solution you'd like
1. Decide what will be the `itm_source` values used. They could all be `wp-parsely` for example, or they could be different between the Content Helper and the Recommendations Block. We could even target specific Content Helper sections with different values, though I have no context about whether this is a good idea or not (@arhine, @danielabloch).
2. Implement the solution.

**Comment by danielabloch** [comment]
My first thought is to create two new `itm-source`: `content-helper` and `recs-block`. It would be helpful to start collecting data on these two separately.

**Comment by GaryJones** [comment]
Maybe also consider a prefix - `plugin-content-helper`, `plugin-recommendations-block` or similar?

**Comment by acicovic** [comment]
I think that prefixing is a good idea. I'd probably prefix with `wp-parsely-`. @danielabloch, what do you think? Also, should we do `recommendations-block` or `recs-block`? Although longer, I do prefer the first variant.

**Comment by danielabloch** [comment]
@acicovic agree on both
prefix: `wp-parsely-`
naming: `recommendations-block`

**Comment by acicovic** [comment]
This was implemented, so closing this.
