### ISSUE TITLE
Incorrect schema for publisher -> logo

### ISSUE THREAD

**Issue by fishsaidno** [Parsely/wp-parsely#150]
Hey there!

It seems the schema for the publisher object generated by this plugin is out of date.
Currently the `publisher.logo` field generated is a string, whereas it should be as below:

```json
{
    "publisher": {
        "@type": "Organization",
        "name": "Google",
        "logo": {
            "@type": "ImageObject",
            "url": "https://google.com/logo.jpg"
        }
    }
}

```
https://developers.google.com/search/docs/data-types/article

**Comment by GaryJones** [comment]
Hi @fishsaidno :-) 

Thank you for reporting this.

Looking at https://schema.org/publisher, it shows that the type is expected to be an `Organization` or a `Person`. Only the `Organization` supports the logo field. All good so far.

When we check https://schema.org/Organization, we can see that `logo` property can be `ImageObject`, or a `URL`, and that is confirmed at https://schema.org/logo.

A https://schema.org/URL is a simple text datatype - a string. The string for a `logo` is demonstrated at https://developers.google.com/search/docs/data-types/logo.

Have you got an example URL which the Rich Snippets Testing Tool says is invalid regarding the `publisher.logo` that uses a string?

**Comment by pauarge** [comment]
Closing this after getting stale.
