### ISSUE TITLE
Incorrect metadata URL when using Plain permalinks structure

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#151]
`Parsely::get_current_url()` strips querystrings, which means it doesn't produce the correct URL when pretty permalinks are not used.

All URLs are the home URL (i.e. `https://example.com` instead of `https://example.com/?p=1` or `https://example.com/?page_id=2` etc.).

**Comment by hbbtstar** [comment]
I suspect this was actually by design, once upon a time: Parsely's backend strips querystring arguments completely, so this implementation followed suit. Given Wordpress' use of the p querystring, I think in addition to fixing this we also have to ask Parsely to explicitly allow the p querystring in its backend (since WP uses it)

**Comment by jblz** [comment]
@hbbtstar Any new thoughts here? Is this something we want to / can support on the service-side?

**Comment by jblz** [comment]
Should we bump this to a later milestone?

**Comment by hbbtstar** [comment]
ah, sorry- I forgot to update this. Yeah, we can make this change: it'll definitely be possible to support these without too much of a lift.

**Comment by hbbtstar** [comment]
oh I missed the second comment: this change won't happen in the Parsely backend in the near term, so it's definitely a candidate for bumping imo!

**Comment by abelsonlive** [comment]
Is there someway within the context of `wp-parsely` for the site admin to indicate that they don't use pretty permalinks? If that information could be passed somehow to the backend upon installation, it would allow us to maintain the `p` or `page_id` parameters without causing issues with other, non-wordpress sites.

**Comment by pauarge** [comment]
Yes, we can tell that from WordPress. However, we can assume that all WordPress sites have it enabled. Even though a site uses _pretty_ permalinks, `?p=` will still be supported.
