### ISSUE TITLE
Parse.ly settings not visible when page contains multiple form elements

### ISSUE THREAD

**Issue by micahwave** [Parsely/wp-parsely#1542]
## Describe the bug
The fields on the Settings > Parse.ly page are not visible to the user if the page contains a form element that appears before the settings page form element.

## To Reproduce

1. Output a `form` somewhere on the page before the Parse.ly settings form appears
2. Navigate to Settings > Parse.ly
3. Observe the the settings are not visible to the user

## Expected behavior
The settings should be visible.

## Screenshots
<img width="1566" alt="Screen Shot 2023-04-07 at 1 30 03 PM" src="https://user-images.githubusercontent.com/481723/230653040-b80a8afb-433b-4a07-aa09-c07a47b4d7d3.png">

## Environment

MacOS, Chrome 111, PHP 8.0, WordPress 6.2

**Comment by acicovic** [comment]
Thank you for reporting the issue and also submitting the fix!
