### ISSUE TITLE
Category pages, 404 pages incorrectly displaying post metadata

### ISSUE THREAD

**Issue by arhine** [Parsely/wp-parsely#155]
The plugin will often return metadata from the first post on the page rather than the metas associated with the page itself. This causes incorrect data to be tracked in the dashboard for both the page as well as the post providing the incorrect metadata.

This behavior is also occurring on some 404 pages, which ideally would not be tracked at all.

This is similar to the behavior for home pages being addressed in https://github.com/Parsely/wp-parsely/pull/152.

Current examples:

* Category page: https://www.eatthis.com/weight-loss/
* 404 page: https://techcrunch.com/my_account

**Comment by GaryJones** [comment]
> 404 page: techcrunch.com/my_account

Techcrunch are running version 2.0 of the plugin; the fix for metadata being added for 404 pages, was [fixed](https://github.com/Parsely/wp-parsely/commit/924cc90be0a239b10705e64c25d8c559ef4e8739) in the 2.2 release.

**Comment by jblz** [comment]
Fixed in #192
