### ISSUE TITLE
Fix errors in utils.php

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1558]
## Describe the bug
Presently we have 2 reports that something is wrong in utils.php

```
Fatal error: Uncaught Exception: Constructor failed
in /wp-content/plugins/wp-parsely/src/Utils/utils.php on line 170

    NumberFormatter::__construct()
    wp-content/plugins/wp-parsely/src/Utils/utils.php:170
    Parsely\Utils\get_formatted_number()
    wp-content/plugins/wp-parsely/src/UI/class-admin-columns-parsely-stats.php:348
    Parsely\UI\Admin_Columns_Parsely_Stats::get_parsely_stats_response()
    wp-content/plugins/wp-parsely/src/UI/class-admin-columns-parsely-stats.php:218
    Parsely\UI\Admin_Columns_Parsely_Stats::enqueue_parsely_stats_script_with_data()
    wp-includes/class-wp-hook.php:308
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:332
    WP_Hook::do_action()
    wp-includes/plugin.php:517
    do_action()
    wp-admin/admin-footer.php:78
    require_once()
    wp-admin/edit.php:502
```

```
An error of type E_ERROR was caused in line 152 of the file /wp-content/plugins/wp-parsely/src/Utils/utils.php.
Error message: Uncaught IntlException: Constructor failed in /wp-content/plugins/wp-parsely/src/Utils/utils.php:152

    #0 wp-content/plugins/wp-parsely/src/Utils/utils.php(152): NumberFormatter->__construct('en', 14)
    #1 wp-content/plugins/wp-parsely/src/UI/class-admin-columns-parsely-stats.php(348): Parsely\Utils\get_formatted_number(256)
    #2 wp-content/plugins/wp-parsely/src/UI/class-admin-columns-parsely-stats.php(218): Parsely\UI\Admin_Columns_Parsely_Stats->get_parsely_stats_response(Object(Parsely\RemoteAPI\Analytics_Posts_API))
    #3 wp-includes/class-wp-hook.php(308): Parsely\UI\Admin_Columns_Parsely_Stats->enqueue_parsely_stats_script_with_data('')
    #4 wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
    #5 wp-includes/plugin.php(517): WP_Hook->do_action(Array)
    #6 wp-admin/admin-footer.php(78): do_action('admin_footer', '')
```

The first occurrence was reported [here](https://wordpress.org/support/topic/error-in-quick-edit-2/). When we first investigated the issue, we concluded that for whatever reason, the host's environment did not support the `NumberFormatter::PADDING_POSITION` constant. So the following test code was always failing:
```php
<?php
$f = new NumberFormatter("en_US", NumberFormatter::PADDING_POSITION);
echo $f->format(10000);
?>
```

## Desired solution
Investigate if the reports boil down to the same issue, and if yes consider an alternative implementation without using `intl`, `NumberFormatter` or `PADDING_POSITION`. 

## To Reproduce
The first customer reported they had the issue when visiting wp-admin's edit.php page. More generally, this error should occur on wp-admin pages that integrate the PCH Stats Column, as it is the component that calls the related functions.

## Expected behavior
The functions in question should work without generating errors or crashing wp-admin.

**Comment by GaryJones** [comment]
> the host's environment did not support the NumberFormatter::PADDING_POSITION constant

The [Intl extension](https://www.php.net/manual/en/intl.installation.php) isn't always installed by default. Having the user confirm if the extension is available (create a page with `phpinfo()`, or running `php -i|grep Internationalization` with CLI access) will likely show it's not. If it is, then NumberFormatter and the PADDING_POSITION constant will be available.

I see four options (not a suggested order):

1. Pull in a Packagist package that provides an alternative to NumberFormatter
2. Create your own alternative function that replicates NumberFormatter
3. Leave the code as is, but add `ext-intl: >=1.0` to the Composer config and make that a documented requirement. `intl` is not a required [extension for WordPress](https://make.wordpress.org/hosting/handbook/server-environment/#php-extensions), but it can help.
4. Check the intl extension/class exists, and only provide the formatted number if it exists. If not, return the unformatted number.

**Comment by acicovic** [comment]
@GaryJones, thanks for flagging that this extension is not always available. This means that we'll need to revise our approach. Also looping-in @mehmoodak for awareness.

**Comment by acicovic** [comment]
Closing this as fixed
