### ISSUE TITLE
Internationalize all user-facing strings

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#160]
To support users who are using the plugin in a locale that is not English, we should let them display strings in their chosen locale. There are two parts to this - wrapping strings in internationalization functions, and providing translated strings. This Issue is concerned with the former.

**Comment by mikeyarce** [comment]
Fixed in https://github.com/Parsely/wp-parsely/pull/226

**Comment by GaryJones** [comment]
There are still JavaScript strings to add i18n functions to yet, but I hadn't tackled them as @jblz was refactoring the JS.

**Comment by jblz** [comment]
The only JS string I see is this one which is now wrapped (as of #236):
https://github.com/Parsely/wp-parsely/blob/3cca62a4c228af6bd8893e744e710fb6b4269e94/src/js/lib/admin-page/index.js#L13-L20

I'm going to go ahead and close this.  Please let me know if I've missed any!
