### ISSUE TITLE
Content Helper: Add engaged time filter

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1661]
**Customer request: show me what content keeps people on our site**
This customer said they need help identifying what keeps people on their site. They want to know which posts people are reading for the longest time, and which posts keep people on site longest / get them to read other content. 

The two metrics that do this:
1 ) engage time
2) recirculation rate (out of scope)

**Acceptance criteria**
Customer can filter the sidebar data by engaged time (new) instead of only page views (old).

**Comment by acicovic** [comment]
The API provides a host of engaged-related metrics (related page [here](https://docs.parse.ly/api-available-metrics/)). No recirculation data at the moment.

Questions that come to mind:
1. Which of the engaged metrics would we like to use?
2. While the sidebar is mentioned in this issue, the Dashboard Widget is probably a good candidate for that feature?

**Comment by danielabloch** [comment]
Yep, recirculation would need to be added to the API. 
I suggest we use `avg_engaged` (Engaged minutes spent by total visitors)
and agreed that it would be good for both the sidebar and the widget

**Comment by acicovic** [comment]
Recirculation is out of scope.  Adding `avg_time` has been done for:
- [x] Dashboard Widget
- [x] Performance Details pane (PCH Sidebar)
- [x] Top Related Posts pane (PCH Sidebar)

**Comment by acicovic** [comment]
Closing this issue as implemented per the work done in #1876 and #1898.
