### ISSUE TITLE
Include more metadata for non-posts

### ISSUE THREAD

**Issue by thompsonjoshua** [Parsely/wp-parsely#1735]
## Is your feature request related to a problem?
Several Parse.ly customers found that their metadata doesn't appear in Dash for non-post pages. 

## Describe the solution you'd like
I would like for the plugin to extract the same metadata fields for non-post pages that posts receive.

## Describe alternatives you've considered
I'm simultaneously pursing a request to the Parse.ly Backend team to enable a new version of the Parse.ly crawler to extract metadata from a wider variety of metadata sources and their respective standards.

## Additional context
During initial development of this plugin, Parse.ly Dash did not support metadata for non-post pages but now it does.

**Comment by acicovic** [comment]
@thompsonjoshua, so the idea here to have total metadata parity between posts and non-posts?

**Comment by thompsonjoshua** [comment]
Yes that's correct. The near-term goal would be adding support for creator/author and section/category values. Adding support for keywords/tags should then achieve that parity.

**Comment by acicovic** [comment]
@thompsonjoshua: I've verified that native WP non-posts (what we would call Pages in WP, located on wp-admin's left-hand menu) don't natively support categories or tags. Author is natively supported in both posts/non-posts.

However, it seems possible to add support for categories and tags to Pages using the `register_taxonomy_for_object_type()` function, and I found a plugin that uses that approach.

So we might have installations where:
- Pages do not support categories/tags (default)
- Pages support categories, tags, or both (custom setup)
- Posts (that natively support categories and tags) are tracked as non-posts, thus currently stripping this information from them (user preference)

To make this feature request possible, we'd probably check whether a non-post actually has categories/tags, and include them in the metadata if it does (author should always be available).

The only complication I can currently think of is cases where users wouldn't want this behavior. Is this something you think we might encounter?

**Comment by thompsonjoshua** [comment]
Thanks! I like the idea of the conditional loading.

While it's always possible that someone doesn't want this behavior, I think the vast majority will support the enhancement. We have a collection of customers with every combination of non-post metadata. 

Most do not have author names, sections, and tags. In such cases we will display a default author name of `Staff`, a section of `Uncategorized`, and no tags. Other customers take advantage of all of the metadata fields. And there are many who are somewhere in between.

It's possible to visit one's [Dashboard Preferences](https://dash.parsely.com/to/settings/preferences) and de-select the enabled aspects to hide some of these features. But that won't provide granular control over posts and non-post pages.

**Comment by acicovic** [comment]
What happens in cases when authors/sections/tags could be disabled per the settings page, but such data actually exists in the metadata? Is it simply ignored?

Edit: Noting that ignored (metadata not being taken into account) and hidden (metadata taken into account but just not shown to users) would be two different things.

**Comment by thompsonjoshua** [comment]
The Parse.ly frontend would hide the metadata from most, but not all places. For example, by disabling the `Author` aspect, there will be no Authors tab and author names won't appear on a post details page. However, one could still run an Author report and filter by author name.

**Comment by acicovic** [comment]
Hi @thompsonjoshua,

Adding `author` / `creator`, `articleSection` and `keywords` to Non-Posts, still leaves Posts with the following extra fields:

- `mainEntityOfPage`
- `thumbnailUrl` / `image`
- `publisher`
- `dateCreated` / `datePublished` / `dateModified`

Should we port these to Non-Posts as well?

**Comment by thompsonjoshua** [comment]
1. I'm not aware of any effect that `mainEntityOfPage` has. This isn't a field that Parse.ly provides explicit support for, based on [this list](https://docs.parse.ly/metadata/#h-parse-ly-s-metadata-fields). You may find a mention of this field in one of our examples [here](https://docs.parse.ly/metadata-jsonld/#h-additional-json-ld-tag-examples) though. I'm not opposed to porting this over, but I also don't know what it does.
2. Adding `thumbnailUrl` / `image` support is a nice to have. It would provide an additional opportunity for distinction in the customer dashboard. Sometimes we find the image outside of the format we request. For example, I found one case where we seem to get the thumbnail from `<meta property="og:image" content="[URL]">`
3. Like `mainEntityofPage`, we don't identify `publisher` as a required field.  I'm not opposed to porting this over, but I  don't know what it does.
4. We do look for publication dates. However, the Parse.ly front end doesn't display this field for non-posts. There may be some functionality with being able to filter by publication date.

If I had to be definitive, I'd say let's grab `thumbnailUrl` / `image` as well as `datePublished`.

**Comment by acicovic** [comment]
@thompsonjoshua, this is being worked on in the PR above, per the specs agreed in this issue.

**Comment by vaurdan** [comment]
It's likely out of the scope for this specific issue, but I think it would be interesting to allow setting up metadata on Custom Post Types, through a filter/action or something similar. Some kind of logic that would allow mapping post fields/post meta to  Parse.ly metadata. If this approach was generic enough, we could use it and extend it to track metadata for pages as well.

**Comment by acicovic** [comment]
@vaurdan, thanks for your input. Unless I'm misunderstanding your thought, this should already be possible for the most part. In the Recrawl section of plugin settings, you can see the core PTs and added CPTs, and select how you want to track them (or disable tracking completely).

<img width="579" alt="image" src="https://github.com/Parsely/wp-parsely/assets/23142906/b65a603b-c208-4232-9e34-2a23a1add707">

This isn't refined to the level you suggest (mapping per field), but you can track as post or non-post, which outputs the metadata differently. The heart of this issue is to enrich non-post metadata to be as complete as post metadata.

There's also a [filter](https://docs.parse.ly/plugin-common-questions/#h-can-the-rendered-metadata-be-customized-or-disabled) that allows users to modify the metadata as desired.

**Comment by vaurdan** [comment]
Ah gotcha, those filters are exactly what I was suggesting :) Please disregard, then!

**Comment by acicovic** [comment]
Per the 2 PRs above, we now have complete metadata parity between Posts and Non-Posts as well as a setting for resolving possible conflicts between the changes and customer code.
