### ISSUE TITLE
Stop tests from echoing

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#180]
It's not a great practice to have tests echo out strings, yet that is exactly what it does for many of the tests - see the [Run integration tests](https://github.com/Parsely/wp-parsely/pull/178/checks?check_run_id=2253518308).

The issue is that the tests call `insert_parsely_page()` ([example](https://github.com/Parsely/wp-parsely/blob/f9007743fefeea3128e9038a97416ce9f7af5c87/tests/all-test.php#L144)), and that includes an [`include 'parsely-parsely-page.php';`](https://github.com/Parsely/wp-parsely/blob/f9007743fefeea3128e9038a97416ce9f7af5c87/wp-parsely.php#L805) that contains markup.

The better approach would be to test the [`construct_parsely_metadata()` method](https://github.com/Parsely/wp-parsely/blob/f9007743fefeea3128e9038a97416ce9f7af5c87/wp-parsely.php#L817) which is [called](https://github.com/Parsely/wp-parsely/blob/f9007743fefeea3128e9038a97416ce9f7af5c87/wp-parsely.php#L804) right before the `include`, to check that the resulting metadata JSON is correct, and not test that PHP has correctly echo'd some content.

Other tests have other variations; giving output for JS, FBIA, AMP etc.

**Comment by mikeyarce** [comment]
Tests to fix:

- [ ] test_parsely_tag
- [x] test_parsely_ppage_output
- [x] test_parsely_categories
- [x] test_parsely_tags_lowercase
- [x] test_parsely_cats_as_tags
- [x] test_custom_taxonomy_tags
- [x] test_use_top_level_cats
- [x] test_custom_taxonomy_as_section
- [x] test_top_level_taxonomy_as_section
- [x] test_http_canonicals
- [x] test_fbia_integration
- [x] test_amp_integration
- [x] test_parsely_page_filter
- [x] test_user_logged_in
- [x] test_user_logged_in_multisite

**Comment by GaryJones** [comment]
#258 fixed most of the echoing tests, but one still remains, so re-opening.

**Comment by jblz** [comment]
The `NOW IT BEGINS` echo previously in `test_parsely_tag` is no more as of #236.  Calling this one (re-)closed!

**Comment by GaryJones** [comment]
<img width="810" alt="Showing non-noisy tests" src="https://user-images.githubusercontent.com/88371/117035638-75061100-acfc-11eb-8fb7-0b4933708f89.png">

🎉
