### ISSUE TITLE
Content Helper: Tag values in Related Top Posts API call should be case sensitive

### ISSUE THREAD

**Issue by randyriback** [Parsely/wp-parsely#1857]
## Describe the bug
Customer's Top Related Posts portion of PCH showing empty results, despite valid tag values present. 

## To Reproduce
Steps to reproduce require screenshots/info that can be retrieved via Slack which include:

- screenshot of customer's supplied tag
- screenshot of customer's empty Related Top Posts component
- Example API call to `/analytics` (which Related Top Posts is built upon) supplied with specific customer tag that is all-caps (results returned)
 - Example API call to `/analytics` with same customer tag supplied as lower-cased (no results returned)

## Expected behavior
API Call via PCH to `/analytics` should match the casing of the supplied tag, or in other words, not be sent exclusively lower-cased, as tags supplied to `/analytics` endpoint are case-sensitive.

**Comment by acicovic** [comment]
Hi @randyriback, thank you for your report. From your report, we assume that case sensitivity in the API is intentional and we'll work on fixing this.

**Comment by acicovic** [comment]
Closing this as fixed. Planned to be released next week.
