### ISSUE TITLE
Content Helper: write title from block of text

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1886]
## Is your feature request related to a problem?
Writing a title for a an article, or a sub-title for an article, is the last thing I do and the last thing I want to do. Can you help me come up with these titles based on what I've already written into the CMS?

## Describe the solution you'd like
Let me highlight a block of text and then show me a title suggestion for that section. 
If I don't like the first suggestion you offer, let me try it again. 
I'd like to see both titles you created next to each other so I can decide which one I want to use or modify.

**Comment by acicovic** [comment]
Closing this as implemented in #1967.
