### ISSUE TITLE
Support REST API output

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#189]
A decoupled app powered by WordPress may want to get Parse.ly constructed metadata for a post/page/archive/home/etc. via the REST API, so that it can be inserted into the decoupled application.

We should find a way to provide that, by adding fields to built-in REST API endpoints, or offering a new route and endpoint.

**Comment by pauarge** [comment]
Duplicate of https://github.com/Parsely/wp-parsely/issues/487
