### ISSUE TITLE
Support GraphQL output

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#190]
A decoupled app powered by WordPress may want to get Parse.ly constructed metadata for a post/page/archive/home/etc. via GraphQL (WPGraphQL plugin), so that it can be inserted into the decoupled application.

We should find a way to provide that. WPGraphQL has a [bunch of extensions](https://www.wpgraphql.com/extensions) which are used to make existing community plugins output to GraphQL.

**Comment by pauarge** [comment]
Related with #487
