### ISSUE TITLE
Content Helper: Remember user settings

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#1954]
## Is your feature request related to a problem?
As settings like `Period`, `Metric` and others are being introduced into the Content Helper, we might be running into usability issues since we're only relying on hard-coded default setting values.

For example, the Dashboard Widget has a default `Period` of 7 days. For some users though, the ideal setting might be 30 days. These users are currently obliged to switch to 30 days manually every time they load the Dashboard Widget.

## Describe the solution you'd like
For certain settings, we should remember the user's last selections and restore them.

**Comment by mjangda** [comment]
This is the user settings api I had mentioned that we could hook into: https://developer.wordpress.org/reference/functions/wp_user_settings/

It stores the values per-user, per-blog in a cookie (so it's available client-side) and in user meta (so it persists across sessions).

We do need to be minimalistic with how much data we store with it though.

**Comment by acicovic** [comment]
Pushing this to the 3.13 milestone so we can make a 3.12 release faster.
