### ISSUE TITLE
New filter request to ignore custom taxonomies from being added as tags. 

### ISSUE THREAD

**Issue by izbatt** [Parsely/wp-parsely#1970]
## Is your feature request related to a problem?
When option `Add Categories to Tags` is selected there is no way for me blacklist custom taxonomies at the taxonomy level. 

## Describe the solution you'd like
I would like a simple filter added where I can hook in and add additional custom taxonomies to ignore, or flat out change the list of ignored taxonomies.
src/Metadata/class-post-builder.php L574 (allow the given array in the array_diff to be modified)
$all_taxonomies = array_diff( get_taxonomies(), **array( 'post_tag', 'nav_menu', 'author', 'link_category', 'post_format' )**;

## Describe alternatives you've considered
I could probably do this in the provided tags filter (wp_parsely_post_tags) but I'd essentially have to undo code that has already run, seems better to just be able to blacklist additional custom taxonomies before they get added. 

## Additional context
File: src/Metadata/class-post-builder.php
function: private function get_custom_taxonomy_values

original: 
private function get_custom_taxonomy_values( WP_Post $post_obj ): array {
    $all_taxonomies = array_diff( get_taxonomies(), array( 'post_tag', 'nav_menu', 'author', 'link_category', 'post_format' );
}

(Something Like)
Modified: 
private function get_custom_taxonomy_values( WP_Post $post_obj ): array {
    $blacklisted_taxonomies = array( 'post_tag', 'nav_menu', 'author', 'link_category', 'post_format' );
    $blacklisted_taxonomies = apply_filters( 'wp_parsely_post_custom_taxonomies', $blacklisted_taxonomies );
    $all_taxonomies = array_diff( get_taxonomies(), $blacklisted_taxonomies );
}

**Comment by acicovic** [comment]
Hello @izbatt. The PR by @norcross has been merged and will be available in the upcoming 3.11.0 release. As such, we assume that this issue can be marked as completed. Feel to reopen it if this isn't the case.

Thank you.
