### ISSUE TITLE
Site ID will not accept URL with hypen in it

### ISSUE THREAD

**Issue by ross-mulcahy** [Parsely/wp-parsely#2006]
## Describe the bug
Some site IDs are not accepted in the plugin setting page

## To Reproduce
Go to Parse.ly plugin settings
Error will appear "The Site ID was not saved because it is incorrect. It should look like "example.com"."

## Expected behavior
Site ID should be saved.

## Environment

Firefox 119.0.1
Mac OS 14.1.1

**Comment by acicovic** [comment]
Hi @ross-mulcahy, I've edited your post for good measure as the Site ID was visible.

This should be fixed with 3.11, which should be in staging tomorrow.

**Comment by ross-mulcahy** [comment]
Confirmed working in 3.11, thank you!
