### ISSUE TITLE
PCH: generate post excerpt 

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#2021]
**Is your feature request related to a problem?**
As a content creator, I'm burdened by having to to tedious work to prepare a post for publication. That includes having to generate an excerpt/summary/brief describing what the post I'm publishing is about.

**Describe the solution you'd like**
When I'm preparing something for publication, I'd like the PCH to help me write an excerpt/summary/brief that I can include in my post and as a metadata description for it. This will save me time!

**Describe alternatives you've considered**
The alternative is that I have to write this myself from scratch. I don't want to do that. Even if I don't use exactly what you create for me, I can use it as a starting point to help me publish faster.

**Additional context**
Validation for this idea came recently on a customer demo of the work in progress.

**Comment by acicovic** [comment]
Done per #2062.
