### ISSUE TITLE
Widget: Duplicate API calls made when multiple instances of the widget are present

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#206]
Related: #158.

As the JavaScript for the widget is loaded in the `widget()` method output, then there is an API call for each instance of the widget that is on the page i.e. two Parse.ly Recommended widgets means two API calls.

If the settings in each widget instance are different (maybe one personalized, maybe one not, or maybe sorted or boosted by different values), then it makes sense to do a request per widget.

When it's the same settings though, then the same results should be returned for all calls, which makes the duplicate requests redundant.

**Comment by mikeyarce** [comment]
I think for this, one approach might be to separate out the JS from the Widget PHP, and then use `wp_localize_script` to send URLs that need to be fetched - then with a list of URLs that need to be fetched we could de-dupe requests there.
Related: https://github.com/Parsely/wp-parsely/issues/158, https://github.com/Parsely/wp-parsely/issues/134
