### ISSUE TITLE
Update the warning message below the Disable JavaScript setting

### ISSUE THREAD

**Issue by jshhnsn** [Parsely/wp-parsely#2073]
## Is your feature request related to a problem?
The current message below the **Disable JavaScript** setting reads:

> WARNING: We highly recommend choosing "No." Disabling the JavaScript tracker will also disable the "Personalize Results" section of the recommendation widget.

This could be more clear as this option is not a recommendation, but rather a requirement if the JavaScript tracker is not implemented elsewhere.

## Describe the solution you'd like
I propose using the following wording instead:

> WARNING: Changing this setting to "Yes" will prevent this plugin from injecting the Parse.ly tracker. Only do so if you are setting the tracker elsewhere (e.g. hardcoded, GTM, another tag manager, etc.).

**Comment by acicovic** [comment]
Hi @jshhnsn, thank you for your suggestion.

I find the suggested message helpful so I'd agree with this change. @danielabloch, would you agree to have us update the text to this?

**Comment by danielabloch** [comment]
@acicovic yes that wording looks good to me

**Comment by acicovic** [comment]
OK, adding this to 3.13.0 as it should be a really quick fix. This is the final wording to be added, with a slight change (`this` to `the`).

> WARNING: Changing this setting to "Yes" will prevent the plugin from injecting the Parse.ly tracker. Only do so if you are setting the tracker elsewhere (e.g. hardcoded, GTM, another tag manager, etc.).

**Comment by acicovic** [comment]
This is now implemented in #2094 and will be part of our 3.13.0 release.
