### ISSUE TITLE
PCH: show list of smart links generated

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#2173]
## Is your feature request related to a problem?
Customers spend more time than they would like finding and embedding links related to an article. The smart links feature (see additional context below) will remove this toil by automatically adding relevant links to a post.

This is fantastic, because it reduces the time someone needs to spend getting a post ready for publication. But how can the customer see which posts we've smart linked in their draft? 

## Describe the solution you'd like
After a customer adds Smart Links to a draft post, show them a list of the related posts that were added to the draft.  Why this is valuable:

- we let customers see what we added to their post
- if they don't like what we added, they can quickly see what they'd like to change, and then do so
- if they do like what we added, it builds confidence in our smart linking capabilities and encourages them to use it more often
- it highlights related posts they might want to revisit, update, or add this draft post to (eg link the articles in both directions)

## Describe alternatives you've considered
The alternative now is not showing them a list of articles included in the post, which is fine but assumes the customer is perfectly content with what we did and does not want to review the results. As this is a new feature and an evolving one, it will help to give them more context with a simple list view.

## Additional context
Here's the issue for the main feature: https://github.com/Parsely/wp-parsely/pull/2116

**Comment by acicovic** [comment]
@danielabloch, we'll need a design/UX flow for this.

I'd probably go with a dialog/panel that allows users to accept or reject the suggested links, and apply them afterwards.

**Comment by acicovic** [comment]
@danielabloch, assigned @vaurdan to this since he's the one who will be working on this. You should continue receiving notifications since you're the author of this issue. If not, notifications can be customized on the right menu in this issue.
