### ISSUE TITLE
Please make monthly increments available for data retention in the Parse.ly dashboard

### ISSUE THREAD

**Issue by nicoleyva30** [Parsely/wp-parsely#2194]
## Is your feature request related to a problem?
This resolves the issue of needing to add on full-year increments each time a customer wants additional data retention. Often, Parse.ly customers have specific date ranges they are looking at, and don't want to include a full additional year to run analysis.

## Describe the solution you'd like
Please make it possible to adjust Parse.ly dashboard data retention by monthly increments rather than just full-year increments. For example, 18 months data retention, 25 months, 30 months etc.

## Describe alternatives you've considered
Quarterly or half-year increments?

**Comment by acicovic** [comment]
@nicoleyva30, seems you've posted this in the wrong repo.

**Comment by nicoleyva30** [comment]
@acicovic I'm sorry! I can delete and re-post, can you point me in the right direction?

**Comment by acicovic** [comment]
Closing this issue (we can't delete it) and I'll forward your request to see where it should be posted.

**Comment by nicoleyva30** [comment]
Thank you!

**Comment by acicovic** [comment]
You're welcome 🙂
