### ISSUE TITLE
Register at packigist.org

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#220]
Our Composer package name is `parsely/wp-parsely`, so this repo should be registered at packagist.org, so that folks can use Composer to install and update, without having to define the repository. Packagist can be configured to keep track of tags and update itself automatically (webhook magic).

Would suggest giving 2-3 relevant people (_maintainers_) the ability to manage the Packagist entry.

**Comment by mikeyarce** [comment]
I added the plugin to packagist but not sure how to add maintainers to the package...  @GaryJones asked them on Twitter!  https://twitter.com/GaryJ/status/1389972227307757568

https://packagist.org/packages/parsely/wp-parsely

**Comment by GaryJones** [comment]
A couple of maintainers to add (the accidentally hidden buttons for the Add Maintainer form is now back), and to make it auto-update, but marking this as done.
