### ISSUE TITLE
Allow NewsArticle schema type to be changed with a filter

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#221]
From https://wordpress.org/support/topic/ldjson-issue/:

> We’ve been using this plugin for content which is not news content.
>
> So, in my copy of the plugin, I’ve changed all instances of NewsArticle to Article.
>
> This… probably means a future problem for me, when the plugin gets updated. But, for now, I thought I should at least put some visibility on the issue…

There are a [few instances of `NewsArticle`](https://github.com/Parsely/wp-parsely/search?q=NewsArticle) that are hard-coded into the plugin.

While `NewsArticle` makes sense as the default, offering a filter here with a post ID and post type would allow a customer to amend what schema `@type` is used on a granular basis. The `after_set_parsely_page` filter is only be able to tackle some instances.

**Comment by htdat** [comment]
Update: Adding only the filter is pretty easy. However, after researching the official guide https://www.parse.ly/help/integration/jsonld/#distinguishing-between-posts-and-pages, I am trying to ensure that the change will have a proper type, and handle the conversion between JSON-LD and Parsely types. 

I have a branch on my computer that is almost ready for this issue, however, I will review it locally before creating a PR for this issue.
