### ISSUE TITLE
Redesign QA

### ISSUE THREAD

**Issue by dabowman** [Parsely/wp-parsely#2275]
Just a place to dump all the little Q/A issues I'm seeing.

**Comment by dabowman** [comment]
I don't think we need the undo option in the snackbar confirmation when you apply a title suggestion. We've already got the confirmation dialog and the option to restore in the sidebar.

**Comment by dabowman** [comment]
make sure dropdowns are the same width as their triggers.
<img width="353" alt="Screenshot 2024-03-08 at 2 22 23 PM" src="https://github.com/Parsely/wp-parsely/assets/5473066/913bcbf6-02dd-4e37-b770-da809a59f417">
<img width="415" alt="Screenshot 2024-03-08 at 2 22 26 PM" src="https://github.com/Parsely/wp-parsely/assets/5473066/c97825f5-c1df-48f9-b8b2-8390868a2b2a">

**Comment by dabowman** [comment]
The little secondary accordions in title suggestions should be the same width as the main panel header accordion. The chevrons on the right should align.
<img width="1085" alt="Screenshot 2024-03-08 at 2 27 31 PM" src="https://github.com/Parsely/wp-parsely/assets/5473066/9b491634-60bd-44a7-a327-ab5005aa4d34">

**Comment by dabowman** [comment]
<img width="1139" alt="Screenshot 2024-03-08 at 2 29 24 PM" src="https://github.com/Parsely/wp-parsely/assets/5473066/9142b9a9-0193-42dc-888b-7c10cec9e524">
In Figma the accordion triggers don't have the same 16px right and left padding as the items inside the accordion.

**Comment by dabowman** [comment]
<img width="136" alt="Screenshot 2024-03-08 at 2 31 24 PM" src="https://github.com/Parsely/wp-parsely/assets/5473066/0349d272-9a79-433f-922c-431e13cbb0fa">
Looks like the fill of this svg got baked in by Figma when you exported it. Should be like the core ones where it get's its color from the css.

**Comment by dabowman** [comment]
<img width="482" alt="Screenshot 2024-03-08 at 2 33 25 PM" src="https://github.com/Parsely/wp-parsely/assets/5473066/1748c6ac-7372-41a0-b8ba-8083c201df6e">
The title suggestions items should be wrapped separate from the trigger. The wrapper should have a 16px gap with 16px padding on left, right, bottom and 6px on the top. There should be no space between the trigger and that wrapper.

**Comment by dabowman** [comment]
<img width="861" alt="Screenshot 2024-03-08 at 2 35 51 PM" src="https://github.com/Parsely/wp-parsely/assets/5473066/7be81985-5817-48f7-bfdf-7988a7a7b06a">
Figma for reference

**Comment by dabowman** [comment]
Looks like this might just be specific to the pinned container. The suggestions container already has a wrapper.

**Comment by acicovic** [comment]
When looking into this issue, we should also look into the patch iteration comments:

- https://github.com/Parsely/wp-parsely/pull/2263#issuecomment-1985365754
- https://github.com/Parsely/wp-parsely/pull/2268#issuecomment-1985189932

@dabowman, some of these comments are addressed towards you. Also pinging @vaurdan here for awareness.

**Comment by acicovic** [comment]
Also, there are a couple of comments in our redesign PR:
- https://github.com/Parsely/wp-parsely/pull/2238#discussion_r1518298471
- https://github.com/Parsely/wp-parsely/pull/2238#discussion_r1518300741

**Comment by vaurdan** [comment]
@dabowman I have 👍 the issues that have been addressed in #2279, which was now merged.

**Comment by acicovic** [comment]
@vaurdan and @dabowman, so it seems all the comments in this thread have been addressed? In this case, the only remaining item is figuring out what to do with https://github.com/Parsely/wp-parsely/pull/2268#issuecomment-1985189932. Let's look/discuss that one shortly, so we close this issue. I'd like us to close it within the interlude if possible.

Also, @dabowman, if you've seen anything else that we haven't addressed, please let us know.

Thank you both! 🙂

**Comment by vaurdan** [comment]
@acicovic The issues discussed in #2268 have been addressed. ([my comment here](https://github.com/Parsely/wp-parsely/pull/2268#issuecomment-2020294952)).

If you agree, this issue can be closed after #2324 is merged.

**Comment by acicovic** [comment]
@vaurdan

> If you agree, this issue can be closed after https://github.com/Parsely/wp-parsely/pull/2324 is merged.

I totally agree, and I've updated that PR's description so this issue gets auto-closed when the PR gets merged.
