### ISSUE TITLE
Add labels for text input fields in settings page

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#229]
Radio buttons and checkboxes have their labels right next to the input, but text input fields don't have a marked up label, unless the `label_for` argument is used with a value of the input `id` attribute, in the custom args parameter for the [`add_settings_field()` function](https://developer.wordpress.org/reference/functions/add_settings_field/) calls.

**Comment by pauarge** [comment]
This should be addressed in conjunction with https://github.com/Parsely/wp-parsely/issues/8

**Comment by GaryJones** [comment]
I'd like to think that this accessibility and usability work could be done in the next release.

**Comment by pauarge** [comment]
My point was that we're going to change the settings page anyway in 3.0, so I'm not sure of fixing it here to change it again in 3.0

**Comment by GaryJones** [comment]
Right - but in between 2.6.0 and 3.0, the fields are inaccessible to some users. And depending on how the revamp for 3.0 goes, the same code may be needed anyway.
