### ISSUE TITLE
PCH Smart Linking: Undo doesn't work for All Blocks option

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#2313]
## Describe the bug
When Smart Linking is applied to all blocks, the undo key shortcut doesn't work. Pressing it doesn't seem to do anything.

## To Reproduce
Apply Smart linking to all blocks in an article, and then try to undo the update with Cmd/Ctrl+z

## Expected behavior
Links should be removed, but instead they remain.

**Comment by vaurdan** [comment]
Closed by #2315
