### ISSUE TITLE
Settings: Improve Site ID

### ISSUE THREAD

**Issue by mikeyarce** [Parsely/wp-parsely#237]
I can enter a variety of Site ID's and they all seem valid:

```
http://mikeyarce.com
https://www.mikeyarce.com
mikeyarce.com
www.mikeyarce.com
```

What is Parse.ly expecting here?  We should make sure to have some validation to make sure the format is what we expect.

Bonus:  We should populate this from the `siteurl` option

**Comment by amontalenti** [comment]
Just a note: a site ID (aka apikey) is "just" a Parse.ly-global string, that so happens to default to the string value of the integration domain (host + tld) upon initial setup. So, if you sign up for the site, `https://automattic.com`, you get given a "site ID" (we also call it an "apikey") of `automattic.com` (assuming it's not taken already). But, your site ID (apikey) could have just as well been `test.automattic.com`, `staging.automattic.com`, or even simply `automattic`. In some other analytics services, e.g. Google Analytics, the equivalent strings have a special format/prefix (e.g. UA-XXX, G-XXX) but in our system it's just a unique string. So there isn't much regex-style validation one could do. That said, it's probably a mistake if this site ID has a URL scheme part (like `http` or `https://`) in it.

**Comment by pauarge** [comment]
Following on @amontalenti point, we don't want to do much validation on the field since the API key is given to the client by the Parse.ly team and has to be added in the Parse.ly back-end (not from WordPress).
