### ISSUE TITLE
Add roadmap.md

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/wp-parsely#24]
To encourage a wider range of users to contribute to wp-parsely, we should develop and maintain a roadmap document hosted here on github that allows users to understand various ways they can contribute to the future of the plugin.

I'll put forward some initial ideas, but will look to others to improve on / curate the list.

**Comment by joshuarrrr** [comment]
bump to 1.13

**Comment by GaryJones** [comment]
At this point, it is easier to put new desired features and known bugs into issues, and assign them a milestone - this is easier to maintain and more dynamic, than having a specific .md file that will quickly become out of date.

Closing for lack of action until this point.
