### ISSUE TITLE
PCH: Consider forwarding main UI errors to Snackbar Notices

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#2424]
## Is your feature request related to a problem?
When users attempt to use AI features but they aren't enrolled into the beta program, we display this message within our Sidebar:

![image](https://github.com/Parsely/wp-parsely/assets/23142906/f1fd869d-daf0-4429-8698-6b986be035ee)

At the same time, there's a Snackbar notice appearing in the bottom left of the Post Editor:

![image](https://github.com/Parsely/wp-parsely/assets/23142906/f0eb844a-7c3f-4c8c-b549-35d2b1238261)

It came to our attention that some users may focus on the Snackbar and wonder about the error, when the reason is stated in the Sidebar. This has been reported once, and we want to avoid this situation as interest in AI features may keep on increasing in the future.

## Describe the solution you'd like
See if we can forward the specific message (or even all error messages) to our Snackbars. This is up to discussion if there are any opinions.

## Describe alternatives you've considered
Removing the Snackbar altogether, but we probably don't need to be that radical 🙂 (cc @dabowman, @danielabloch).

**Comment by danielabloch** [comment]
`Request access here <link to form> to use this feature.`
Thinking ^ we could change the message to this to reinforce the sidebar message.

**Comment by acicovic** [comment]
@danielabloch, so the whole message would be:

> This Al-powered feature is opt-in. Request access [here](#) <link to form> to use this feature.

Correct?

**Comment by danielabloch** [comment]
I was thinking we only use the second sentence because the message is really long...but I can see how omitting the first sentence makes it confusing as to why you have to request access....

`Request access here to use this opt-in feature. ` <-- maybe this? or do you think the full message is an acceptable length?

**Comment by acicovic** [comment]
@danielabloch, the message itself isn't a difficult change for us, so feel free to discuss it with anyone else if you want. I think that your latest message is fine, although I also see usefulness in mentioning that this is an AI feature. This way, everyone is aware.

**Comment by danielabloch** [comment]
Let's use the fuller message for the added context. 
`This Al-powered feature is opt-in. Request access [here] to use this feature.`

If it's too long for the snackbar notification, we can use the short message instead.  
`Request access [here] to use this opt-in feature. `

**Comment by acicovic** [comment]
Hey @danielabloch,

After trying this, it seems we cannot have a link within the snackbar's body. However, we can have a separate link next to it, like so:
<img width="391" alt="image" src="https://github.com/Parsely/wp-parsely/assets/23142906/e34f3c3b-d0fa-44e7-a3d7-91432cb18f90">
This changes the structure of our text a bit. Let me know how we want to amend the texts, or if this is fine.

If we don't like this, we could remove the snackbar altogether when this condition occurs. The message will still be visible in the sidebar, per the first screenshot in the first post of this issue.

**Comment by acicovic** [comment]
To follow-up, another thing I discovered is that [links in these notices cannot open in a new tab](https://github.com/WordPress/gutenberg/issues/20876), which is what we're doing in the Sidebar as to avoid breaking context for the user.

Due to this restriction, if a user has changes in their post and click the notice's link, they will need to cancel a browser warning dialog, save the changes in their post, and by that time the notice will be gone (even if it's set to explicitly dismiss). So they'll need to re-click the feature button to get the notice again.

Besides the different behavior from the sidebar notice, I find this whole thing to be a very suboptimal user experience. As such my final suggestion is to not show a snackbar notification when the specific condition occurs. All other messages will display their details as expected, per the work in #2579.

Let me know of your thoughts.

**Comment by danielabloch** [comment]
Absolutely agree. Let's not show a snackbar at all. 
- The existing message is too confusing. (hence this issue having been created!)
- The snackbar as you showed it above is great, but if it takes people away from the page they are editing, it is not an option we should ever consider.

**Comment by acicovic** [comment]
We're taking care of this now in #2601.
