### ISSUE TITLE
PCH Excerpt Generator: "Error: undefined" notification

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#2472]
## Is your feature request related to a problem?
When users attempt to use the AI-powered excerpt generator, but do not have access to it, they see  this message:
<img width="101" alt="error-undefined" src="https://github.com/Parsely/wp-parsely/assets/88679146/cd547914-205e-461f-8f9c-8c8bc98a8493">

Related to the snackbar updates we want to make in the Tools tab of the PCH: https://github.com/Parsely/wp-parsely/issues/2424

## Describe the solution you'd like
Repeat the same message we show in the Tools tab of the PCH to customers who do not yet have access to the AI features.
![image](https://github.com/Parsely/wp-parsely/assets/88679146/a23709d6-4a13-4a23-9355-8207fe305104)

## Describe alternatives you've considered
None, because we decided on and implemented this message for other AI powered features. With this request we ensure the same message shows for all features.

**Comment by acicovic** [comment]
We've only seen this happen once. It surfaced on the VIP platform under circumstances which aren't entirely clear to us currently. It could need some special debugging to possibly be reproduced.

Although we haven't worked directly on this specific issue, much of the code in that area has been revamped when we were working on https://github.com/Parsely/wp-parsely/pull/2601, https://github.com/Parsely/wp-parsely/pull/2579, and https://github.com/Parsely/wp-parsely/pull/2580.

As such, this edge case might already be solved and I'm closing this issue. If we stumble upon it again, we'll reopen!
