### ISSUE TITLE
Not escaping unicode quotes properly

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/wp-parsely#25]
The New Yorker is using our WP Plugin and have recently run into an issue where some posts are not surfacing in the dashboard. Upon inspection, these posts are being discarded due to improperly escaped quotes. However, the quotes that are not properly escaped are the unicode equivalent of a double quote. ( " )

I've copied a few of the missing posts below:

http://www.newyorker.com/tech/elements/holocene-anthropocene-human-epoch

http://www.newyorker.com/culture/cultural-comment/possessed-james-brown-eighteen-minutes

http://www.newyorker.com/culture/cultural-comment/invisibilia-evolving-art-radio

In the first URL above, here is the part of the metadata tag that is breaking the tag.

tags; magazine","anthropocene","extinction","fossils","geologists","geology","holocene","jan zalasiewicz","nuclear weapons","stratigraphy","the european discovery of america","post_type: post"]}'

The first of the above tags has the unicode double quote and it is not escaped. Do we need to apply a change to our WP plugin? Or is this something that is happening on the New Yorker's end?

**Comment by dan-blanchard** [comment]
I don't think this was an issue on our end.  I did fix a minor bug that's somewhat related (see [this change](https://github.com/Parsely/wp-parsely/blob/84ec1eba1a114929e17ef6badf03f2954917e4c4/wp-parsely.php#L334)), but whenever I use fancy unicode quotes in the tags, they just get turned into `\u201c` and `\u201d` in the output.  I'm going to say that this is probably a problem with how they have their [WP/PHP multibyte string stuff setup](http://sundayepidemic.com/wordpress-mbstring/).  They already went back and manually fixed the errors, so I can't even see exactly what it looked like when they had problems.
