### ISSUE TITLE
Remove type=text/javascript instances

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#255]
There may be a few instances of `type='text/javascript'` (and with double-quotes) in code and test files. This attribute can be removed since `text/javascript` is the default value for the `script` element in HTML5 when the `type` attribute is omitted.

> The HTML5 specification urges authors to omit the attribute rather than provide a redundant MIME type.
– https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by GaryJones** [comment]
Only instance appears to be in `parsely-admin-header.php`, which should be removed in #236.

**Comment by jblz** [comment]
Just noting that there's a `type='text/javascript'` added by core in a few spots.

Most notably, if the theme does not satisfy support via `current_theme_supports( 'html5', 'script' )`, the type attribute is added in at least these places:

* https://github.com/WordPress/WordPress/blob/4a73e53df40cb6575e957bd52520e00f8601ff5b/wp-includes/script-loader.php#L1967
* https://github.com/WordPress/WordPress/blob/4a73e53df40cb6575e957bd52520e00f8601ff5b/wp-includes/script-loader.php#L2422
* https://github.com/WordPress/WordPress/blob/4a73e53df40cb6575e957bd52520e00f8601ff5b/wp-includes/script-loader.php#L2466

...so in #236, it still exists in the test as, we're not declaring such support.

Probably nothing to change, but thought I'd note it here for posterity.

**Comment by GaryJones** [comment]
Interesting, and good catch.

I think it would be worth having the test add the theme support, and then removing the `type` attribute from the expected values in the tests.

HTML 5 was a [W3C Recommendation since 2014](https://www.w3.org/TR/2014/REC-html5-20141028/), and theme support for it has been added back to the [Twenty Thirteen theme](https://github.com/WordPress/WordPress/blob/589e89231a53e47e57a58a35a97d9e772d8f7cf9/wp-content/themes/twentythirteen/functions.php#L161-L173), so 7-8 years seems long enough to go with it as the basis of our tests as well.
