### ISSUE TITLE
PCH: include excerpt generator in Content Helper sidebar panel

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#2552]
## Is your feature request related to a problem?
When using the Parse.ly Content Helper, customers are not aware that we offer smart excerpt generation (powered by their performance data + our ML system/AI). This means one of the capabilities we built is unknown and thereby unused by customers.

## Describe the solution you'd like
Include the existing excerpt generation feature in the Parse.ly Content Helper panel in Block Editor interface

Excerpt generator in main Post tab for WordPress settings
<img width="275" alt="excerpt feature" src="https://github.com/Parsely/wp-parsely/assets/88679146/81cd3d78-d781-4ea8-bd17-09a4f3a62c1f">

Where it should be also added > Content Helper tools tab
<img width="283" alt="add excerpt feature" src="https://github.com/Parsely/wp-parsely/assets/88679146/4e6176f2-c2f8-45e9-881d-ee8b08bcf8f3">

Its placement should be below Title Suggestions and above Smart Linking because that is its logical placement within the publishing workflow

## Describe alternatives you've considered
N/A

## Additional context
After discussing it, we see no harm in offering the feature in both the WP settings tab and PCH tab so please keep it in the former and add it to the latter

**Comment by acicovic** [comment]
@danielabloch, @dabowman, we might choose to integrate this into 3.17.0, relatedly to the work on #2776.

To know how to proceed though, we need to decide if we want to host the Excerpt Suggestions feature under the PCH Sidebar as a UI (like in Post Settings) or as a link to the existing tool.

**Comment by danielabloch** [comment]
i still prefer having it be UI like in Post Settings 
mentioned in slack that it would be helpful to note in the UI if a brief has already been generated when someone is looking at it in PCH or the main sidebar

**Comment by acicovic** [comment]
OK, we'll look into adding it as a UI. 🙂

**Comment by acicovic** [comment]
I'll move this to the 3.17.0 milestone, as it makes sense to pair it with #2776. @vaurdan, let me know about any possible thoughts or objections to that.
