### ISSUE TITLE
Add WordPress.org banner images

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#259]
Extracted from #186:

Docs: [developer.wordpress.org/plugins/wordpress-org/plugin-assets](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets)

The following banners can be added:

- Normal Banner: `banner-772x250.(jpg|png)`
- Normal Banner (RTL): `banner-772x250-rtl.(jpg|png)`
- High-DPI (Retina): `banner-1544x500.(jpg|png)`
- High-DPI (Retina RTL): `banner-1544x500-rtl.(jpg|png)`

The RTL versions are only needed if the LTR banner doesn't look good for RTL locales.

The High-DPI versions don't work on their own - the Normal banner needs to be present as well.

Should all be saved to `.wordpress-org` directory, as the GitHub action workflow will look there for them by default and push to the SVN `assets` directory.

These will then appear on https://wordpress.org/plugins/wp-parsely and localized variants (e.g. https://ar.wordpress.org/plugins/wp-parsely)

See https://wordpress.org/plugins/wordpress-seo and https://ar.wordpress.org/plugins/wordpress-seo as an example of the banners in action.

**Comment by acicovic** [comment]
Hey there,

@jase-d-ace will be helping us with banner creation.

**Comment by acicovic** [comment]
So here's the first version of the banner images we got. Personally I'm fine with this.

Contributors, let us know if you approve this or if anyone has suggestions to improve it. Feel free to let us know if you think this should be improved or changed. I'm also mentioning @jblz here in case he isn't subscribed to this thread but does want to provide feedback.

Thanks!

<img width="772" alt="772x250" src="https://user-images.githubusercontent.com/23142906/147654143-98028eed-ccbf-4c11-9e35-100a94b9b7bb.png">

<img width="1544" alt="1544x500" src="https://user-images.githubusercontent.com/23142906/147654227-128f8eca-b0d5-4d64-88c6-702f673b604b.png">

**Comment by GaryJones** [comment]
Should that be just the WordPress logo, or should it be a WordPress VIP logo?

As noted, for RTL locales, the banner will be "read" with the WordPress logo first.

**Comment by jase-d-ace** [comment]
If I'm not mistaken, I believe our plugin will be available to all WordPress users, not just VIP ones, so we decided on the standard WordPress logo over VIP. If this is not the case, we can make the change to the VIP logo instead. As for the RTL locales, does the order of which logo is "read" first matter? Or is it that the logos will be "mirrored" and will look incorrect in an RTL locale?

**Comment by acicovic** [comment]
Hello there,

@GaryJones My understanding is that the plugin is non VIP-specific and is available in the public plugin repository (someone shouldn't need to be a VIP client to use it) so it was me who brought up the WP logo. This suggestion was made on the premise that the requirements are WP + Parse.ly.

@jase-d-ace I think that the point that @GaryJones tries to make is that those who read in an RTL fashion will see the WP logo as "first" and the Parse.ly logo as "second". In our case this might not be of any significance, but if you wanted them to see the Parse.ly logo as "first" you would produce the same image with the logo order inverted. The image should display fine in RTL (no mirroring).

**Comment by jase-d-ace** [comment]
@acicovic I think we're fine with the rtl being that way, so it's not a blocking issue on our side either.

**Comment by acicovic** [comment]
OK, I'll keep this open for a few days in case anyone would want to comment further.

**Comment by GaryJones** [comment]
Yes, the plugin is available to everyone, yet so is the Parse.ly service itself, but the logo on https://parse.ly includes "Part of WordPress VIP". My suggestion is related to marketing / branding, and not "what host does the plugin work on".

**Comment by pauarge** [comment]
Tagging @kbourgoin and @amontalenti for their input on this one.

**Comment by acicovic** [comment]
If @kbourgoin and @amontalenti can help that's great! It would also be good to know that we're getting an "OK" from the VIP side.

**Comment by kbourgoin** [comment]
Looks good to me! Let's go with these.  👍

I think that for this it's more important that it be clear Parse.ly works with all of WordPress and not just WordPress VIP. Putting a more restrictive logo in place could lead to needless confusion.

If we were designing a banner for a Drupal plugin, then the banner would have the Drupal logo in that spot. Therefore, it seems logical that this should be the WordPress logo, and not WordPress VIP.

**Comment by acicovic** [comment]
@jase-d-ace I took the liberty to resize the 3088x1000 version to 772x250 (didn't exist in my received files), which resulted in a 23,05KB file. If you have a better/smaller version you can always send it to me and I'll update it.
