### ISSUE TITLE
Support custom Section field option

### ISSUE THREAD

**Issue by aldraco** [Parsely/wp-parsely#26]
Some publishers use custom variables instead of Section; unfortunately this means that their "section" keys are null when passed as is through the wp plugin.

Could we add a feature kind of like "use sections as tags" that allows publishers to specify what field they're using as their section?

**Comment by hbbtstar** [comment]
addressed in https://github.com/Parsely/wp-parsely/commit/33730b78a81753c009979a4f8b69411668dfa536, closing out!
