### ISSUE TITLE
Errors when editing widgets inside of Customizer

### ISSUE THREAD

**Issue by laurelfulford** [Parsely/wp-parsely#2684]
## Describe the bug
When you're running the latest version of the Parse.ly plugin (v. 3.16.2) and using a theme with a widget area, the widget screen on the Customizer will throw errors.

## To Reproduce
1. Start on a test site using a theme with widget areas, like Twenty Twenty One, Twenty Twenty, or earlier. 
2. Activate v. 3.16.2 of the Parse.ly plugin (you don't have to have it correctly connected, just activated).
3. Navigate to Customizer > Widgets, and select a widget area to edit.
4. If there are already widget, you'll see the error; if there aren't try to add one, and it will be thrown. There will also be JS errors in the element inspector related to the Parse.ly plugin, like:

```
TypeError: lt is undefined
    ut [URL]/wp-content/plugins/wp-parsely/build/content-helper/editor-sidebar.js?ver=69283974093cc5f88771:6
```

Editing widgets under Appearance > Widgets still works as expected.

## Expected behavior
That the widgets will display correctly, and no JavaScript error will be thrown.

## Screenshots
![image](https://github.com/user-attachments/assets/3df5162c-5d3a-4e7b-b347-7f48407fbf65)

## Environment
OS X 12.6.4, Firefox 128.0.3, WordPress 6.6.1. Only Parse.ly and Twenty Twenty One active.

## Additional context
This is affecting all Newspack sites, since they use both a theme with widget areas, and the Parse.ly plugin.

**Comment by shelb-elliott** [comment]
Just stopping in to +1 this. I have two Newspack Publishers reporting this issue currently.

**Comment by acicovic** [comment]
Hello and thank you both for the report and feedback!

We'll see if we can expedite this in a patch release, as our next planned release could take some time.

**Comment by acicovic** [comment]
This issue has been fixed and merged in version 3.16.3, which is [immediately available](https://wordpress.org/plugins/wp-parsely/).

**Comment by laurelfulford** [comment]
Thanks for the quick fix, @acicovic! 🙌

**Comment by acicovic** [comment]
You're welcome! Credit for the fix and release goes to @vaurdan! 🙂
