### ISSUE TITLE
Excerpt Suggestions: Allow different personas/styles

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#2692]
## Is your feature request related to a problem?
In Excerpt Suggestions, we currently don't offer a way to customize the persona and style. We recently received internal feedback that this would be desirable, since the current persona/style isn't ideal for writings of certain types (e.g. documentation).

## Describe the solution you'd like
Provide controls to specify persona and style, as we currently do in our Title Suggestions feature.

**Comment by jbao** [comment]
Re: the feedback on excerpt suggestion specifically, it also has to do with the fact that currently we explicitly ask the LLM to include a call-to-action in the response. We might also want to make that configurable.

**Comment by acicovic** [comment]
Ah, I thought that this had to do with the persona/style, not that there's a specific prompt that does that. Maybe this is something to talk about.

**Comment by acicovic** [comment]
There's [WIP](https://github.com/Parsely/wp-parsely/pull/2776) regarding this feature request. It doesn't address the call to action text in the end of the excerpt though, since this is API code as stated by @jbao. If adjustments to the API are made, we can see if we require a control (e.g. a checkbox) on the plugin side.

cc @danielabloch for awareness.
