### ISSUE TITLE
PCH features cannot be disabled for Super Admins

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#2874]
## Describe the bug
It has come to our attention that disabling PCH features doesn't work for Super Admins. Whether we uncheck the Administrator User Role, a specific feature or all AI features, Super Admins still see and can use the features that have been disabled in settings.

## To Reproduce
1. Login as a Super Admin.
2. In the plugin settings under the "Content Helper" tab, disable the "Administrator" User Role, a feature, or all AI features.
3. Go to the PCH Sidebar.

Instead of the disabled features being invisible and inaccessible, they are shown and are totally operable by Super Admins.

## Expected behavior
The disabled features should not be available to Super Admins.

## Additional context
Our testing indicates that this bug only affects Super Admins. PCH permissions should be applied correctly to other User Roles.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by acicovic** [comment]
Fixed in https://github.com/Parsely/wp-parsely/pull/2895, shipping in 3.17.0.
