### ISSUE TITLE
PCH Sidebar Stats: Investigate displaying data for already published "future" posts

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#2881]
## Is your feature request related to a problem?
Here's the problem statement, expressed by a customer:

> We utilize the "future" post status in WP for stories that have already been published, but have a future update scheduled to publish. Unfortunately, the Parse.ly plugin sees that "future" status and won't attempt to pull analytics data – the user sees an error message that the story hasn't yet been published, which isn't true.

To give some context, we use the `select( 'core/editor' ).isCurrentPostPublished()` function, which is a core WP/Gutenberg function. This means that Gutenberg itself considers the post non-published.

Having published future posts could be characterized as an edge case, but we've decided to investigate to see if there's a graceful solution for this. To quote @vaurdan:

> Interesting use case. The standard use case for future post status is for posts that are scheduled to be published in a future date, therefore shouldn't have a public URL yet, nor have any analytics. But it seems that the default behavior is overridden so that future posts are indeed published.

> A possible solution to make this more flexible, would be to check only for the permalink - [like we do here](https://github.com/Automattic/vip-go-mu-plugins-built/blob/9ed0bbf924b1ca937515490675c5f8a16b3bd09a/wp-parsely-3.16/src/content-helper/editor-sidebar/performance-stats/provider.ts#L72-L81) - and skip the `isCurrentPostPublished` check. If there is no permalink, it means the post isn't published and never was. This would require some additional testing to make sure we cover any edge cases, but it might be a solution.

## Describe the solution you'd like
As the posts might already have a temporary permalink assigned to them, this solution might not be an option. So the first step is to investigate this potential solution, to determine if it is a valid one.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by acicovic** [comment]
Moving this into the 3.17 milestone so we can have a solution in our upcoming release, or determine that this issue is a `wontfix`.
