### ISSUE TITLE
Make cfasync script attributes opt-in

### ISSUE THREAD

**Issue by jblz** [Parsely/wp-parsely#293]
## Is your feature request related to a problem?

As mentioned [here](https://github.com/Parsely/wp-parsely/pull/286#issuecomment-833474663), there's no need to have these attributes in place for sites that don't use Cloudflare.

It should, therefore, be opt in.  Since it's a breaking change, I'm adding it to the 3.0.0 milestone.

## Describe the solution you'd like

Either a checkbox in the "Advanced" settings section or a filter to opt-in to this behavior (I'd lean toward the latter).

**Comment by GaryJones** [comment]
+1 for the filter approach, and not having a new setting.

We could also make this opt-out for a 2.6.0 release, and then opt-in for the 3.0.0 release.
