### ISSUE TITLE
Drop Support for IE11 Alongside WordPress 5.8

### ISSUE THREAD

**Issue by jblz** [Parsely/wp-parsely#325]
WordPress core is in the process of [dropping support for Internet Explorer 11](https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/) and steps to do so have already begun [making their way into the front-end build tooling](https://github.com/WordPress/gutenberg/pull/31110).

Our trusty dependabot has opened the following PRs against our dev dependences to that end:
#319
#320
#322

Do we want to go forward with this change for 2.6?

**Comment by GaryJones** [comment]
WP 5.8 is due at ~the end of the year~ July 20 - Parse.ly 2.6 would be out before then, so maybe aim for Parse.ly 2.7 or 2.8?

**Comment by jblz** [comment]
Marked those PRs as "ignore this major version"

We'll reopen / revisit once WP 5.8 ships.
