### ISSUE TITLE
Compatibility with official Wordpress FBIA plugin

### ISSUE THREAD

**Issue by jtotoole** [Parsely/wp-parsely#33]
Per Wordpress: 

"We've added a couple of compat layers into the FBIA plugin for some common plugins, but we can also do this outside of the plugin. That'd probably be better for you, as you can maintain that code yourselves without relying on us and it can sit alongside the AMP integration.

The Google Analytics code is a good example: https://github.com/Automattic/facebook-instant-articles-wp/blob/master/compat/class-instant-articles-google-analytics-for-wordpress.php

In the Parse.ly plugin, you could add a class with a similar structure.

The key bit is to hook into instant_articles_compat_registry_analytics to register your compatibility layer with the FBIA plugin.

Then, get_raw_embed_code() simply returns the HTML. This HTML is then put through the Facebook Instant Article SDK to produce FBIA-compatible markup.

In the GA example you can see that get_raw_embed_code() goes elsewhere to fetch the code, but you can do that however works best for you."

**Comment by hbbtstar** [comment]
closed with https://github.com/Parsely/wp-parsely/pull/48
