### ISSUE TITLE
Unused Variable: Default Logo

### ISSUE THREAD

**Issue by jblz** [Parsely/wp-parsely#330]
Noticed while stepping through phpcs issues:

At:
https://github.com/Parsely/wp-parsely/blob/e1c3e43d98ce7e45d4c990421a690a677abdf829/src/class-parsely.php#L386

This variable is set, but never referenced:
`$option_defaults['logo'] = $this->get_logo_default();`

It looks like the intent is to populate the private member variable declared here:
https://github.com/Parsely/wp-parsely/blob/e1c3e43d98ce7e45d4c990421a690a677abdf829/src/class-parsely.php#L48

The `get_logo_default` method is also called in the `validate_options` method here:
https://github.com/Parsely/wp-parsely/blob/e1c3e43d98ce7e45d4c990421a690a677abdf829/src/class-parsely.php#L647-L649

...so I think it's ok to just remove L#386, but we should make sure the default logo is being set appropriately.

**Comment by GaryJones** [comment]
Agreed - it possibly was meant to be `$this->options_default['logo'] = ...` at one point, but right now, it's not doing anything and can be removed.
