### ISSUE TITLE
Find fallback image when featured image isn't set

### ISSUE THREAD

**Issue by jtotoole** [Parsely/wp-parsely#34]
In wp-parsely.php, the fallback if a post doesn't have a featured image is just "" (set [here](https://github.com/Parsely/wp-parsely/blob/master/wp-parsely.php#L345)). 

Since a lot of blogs don't set featured images, has_post_thumbnail() will return false a lot. It looks like a lot of people work around this by searching for the first image in the blog post using this code: https://css-tricks.com/snippets/wordpress/get-the-first-image-from-a-post/

^thx @meniltiac!

**Comment by hbbtstar** [comment]
fixed in https://github.com/Parsely/wp-parsely/commit/b08b8ce76f556b04d1aae3b44154fcd62acf733d
