### ISSUE TITLE
[Backlog Item] Clean Up Wipe Metadata flow in the React settings page

### ISSUE THREAD

**Issue by jase-d-ace** [Parsely/wp-parsely#342]
## Describe the bug

0% priority. In the process of sprinting to the end of v1.1 of the new React settings page, the flow for wiping customer metadata takes too many steps, where the user has to open the modal, type their site ID, click confirm, and then submit the form to actually do it. At some point someday, I'd like to make it so that metadata is wiped upon clicking confirm, in a workflow completely separate from the rest of the form, just so it's in line with other website's confirmation flows (like github's Delete Repository functionality).

## To Reproduce
1. Go to the Debug tab of our new React settings page ([branch here](https://github.com/Parsely/wp-parsely/tree/remove/jquery-dependency--try-react))
2. Click on Wipe Your Metadata?
3. Type in your site ID and click Confirm
4. Submit the form <----- this step should be cut

## Expected behaviour
Ideally we should wipe metadata after the modal flow instead of waiting to submit the whole form, as that's just unnecessary extra steps if all the customer is doing is wiping metadata (for whatever reason).

## Additional context
I'm wondering if we can send our settings API pieces of a settings object (e.g. only send the field where we set `wipe_metadata` to `true`). If so, this would be pretty trivial to do, as it would only require sending the relevant K/V pair, instead of having to go through the dance of copying current state, changing a field, and then sending that.

Again, this is super NOT a priority, especially since our React page isn't even live yet. But it's something that I think we should be thinking about at some point.

**Comment by pauarge** [comment]
Closing this issue because we won't be pursuing the React-based settings page.
