### ISSUE TITLE
CI: Update to use default npm caching

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#348]
https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

Review whether we can update our node GitHub Actions workflow to make use of this caching, and remove the extra caching step that exists.

**Comment by pauarge** [comment]
We're actually already using this on the E2E tests: https://github.com/Parsely/wp-parsely/blob/cf54b1fea36142698b1796dacee1988747f27beb/.github/workflows/e2e-tests.yml#L29
