### ISSUE TITLE
Widget not populating recommendations for customer's staging site

### ISSUE THREAD

**Issue by arhine** [Parsely/wp-parsely#359]
For Parse.ly customer site stage.adweek.com, the Recommended widget is not serving recommendations on the page. A review of the console doesn't indicate the call to /related is being made.

**Example page**: https://stage.adweek.com/convergent-tv/nbc-sports-enlists-innovid-for-tokyo-olympics-ad-management/. 
Note the Recommended header in the right rail. Recommendations should appear below.

API secret has been confirmed as valid, and running an API query with the same parameters as those provided by the widget returns valid data. So the issue appears limited to the plugin.

**Current widget settings:**
![Screenshot](https://user-images.githubusercontent.com/684746/129029036-74471227-9b54-4a3e-b153-7d7165f10f5e.png)

**API query with results:**
https://api.parsely.com/v2/related?apikey=stage.adweek.com&url=https://stage.adweek.com/convergent-tv/nbc-sports-enlists-innovid-for-tokyo-olympics-ad-management/&sort=score&boost=views&limit=10&page=1

**Comment by pauarge** [comment]
We are currently working on fixing some known issues in the widget. We are aware of them and should be rolled out as a fix.
