### ISSUE TITLE
Check for wpcom_vip_get_term_by before using get_term_by

### ISSUE THREAD

**Issue by jtotoole** [Parsely/wp-parsely#37]
`wpcom-vip_get_term_by` is the cached version of `get_term_by`, though it's not part of the Wordpress core. We should make a new function to check for the existence of the former before falling back to the latter. That would look something like:

```
public function parsely_get_term_by(args) {
    if( function_exists('wpcom_vip_get_term_by') ) {
        wpcom_vip_get_term_by(args);
    } else {
       get_term_by(args);
    }
}
```
Lines to be changed:
https://github.com/Parsely/wp-parsely/blob/master/wp-parsely.php#L670
https://github.com/Parsely/wp-parsely/blob/master/wp-parsely.php#L672
https://github.com/Parsely/wp-parsely/blob/master/wp-parsely.php#L700
https://github.com/Parsely/wp-parsely/blob/master/wp-parsely.php#L707

**Comment by hbbtstar** [comment]
fixed in https://github.com/Parsely/wp-parsely/commit/79ed4b715cd6b8861db9e221b86a4e19057b532e
