### ISSUE TITLE
Consider changing the default value of `meta_type` to `repeated_metas`

### ISSUE THREAD

**Issue by jblz** [Parsely/wp-parsely#372]
## Is your feature request related to a problem?

If a site has an existing schema.org structure and strategy, it's possible that the inclusion of our structured data in the same `ld+json` format could have adverse (or at least unexpected) effects which bespoke `<meta name="parsely-...` tags do not manifest. 

## Describe the solution you'd like

Consider changing this line:
https://github.com/Parsely/wp-parsely/blob/e196413774b645423fe7022dc4b0e2742620a534/src/class-parsely.php#L47
to have default value:
`repeated_metas`

This would not alter sites that are currently running the plugin, but new sites that activate the plugin will get the new default.

## Describe alternatives you've considered

...not doing this :)

**Comment by pauarge** [comment]
I'm not really sure about this. I see your point, but it's breaking a default behavior and might cause some confusion. I think that it's pretty clear how to change from one method to another in the settings page and our support team is fully aware of it.

Do you think it's worth doing some additional investigation or could we close the ticket @jblz?

**Comment by jblz** [comment]
I think @hbbtstar mentioned at some point that changing the default to repeating metas might be desirable. 

As mentioned, this change would only affect new installs without a set option. 

As to any tradeoffs to repeated metas, I'm not aware (cc @kbourgoin in case he's aware of any).

We've been running this as the default on some subset of VIP per [this line](https://github.com/Automattic/vip-go-mu-plugins/blob/3c7da457bb0e6deec387f9897dfef2ade674b47b/wp-parsely.php#L129).

**Comment by kbourgoin** [comment]
Both options are well supported in the crawling infrastructure. They each have their pluses and minuses. JSON-LD is good for folks who want the extra bump from Google for having well-formatted metadata. Some SEO ~charlatans~ professionals claim it causes more harm than good, but we've never seen that be the case.

I think either one as a default is pretty reasonable and using repeated-metas is less likely to interfere with anything else on the page.

**Comment by pauarge** [comment]
Given that there's no choice that's overwhelmingly better than the other, I'd rather keep the plugin stable and not change things. Happy to revisit this issue in the future if circumstances change.
