### ISSUE TITLE
Consider pre-push hooks

### ISSUE THREAD

**Issue by jblz** [Parsely/wp-parsely#375]
## Is your feature request related to a problem?

Doing some checks locally prior to pushing to a remote branch will:
* provide a tighter development feedback loop for changes that are destined to be rejected by CI
* reduce load on CI for pushes that would be destined to fail

## Describe the solution you'd like

Implement [husky](https://github.com/typicode/husky) pre-push checks (or similar solution) for common cases of failing CI runs:
* uncommitted changes
* phpcs violations
* eslint violations
* etc.

## Describe alternatives you've considered

:hulksmash:

**Comment by pauarge** [comment]
This is being addressed in https://github.com/Parsely/wp-parsely/pull/344
