### ISSUE TITLE
Remove post_has_viewable_type function

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#381]
## Is your feature request related to a problem?

This function is simply a wrapper around `is_post_type_viewable`, which [got introduced in WordPress 4.4](https://developer.wordpress.org/reference/functions/is_post_type_viewable/). The function offers a fallback for earlier WordPress versions, prior to 2015.

We should use `is_post_type_viewable` directly.

## Describe the solution you'd like

We should raise the minimum WordPress version to 4.4 and replace all the calls to `post_has_viewable_type` with `is_post_type_viewable`.

**Comment by GaryJones** [comment]
https://github.com/Parsely/wp-parsely/blob/develop/wp-parsely.php#L22 and https://github.com/Parsely/wp-parsely/blob/develop/README.md?plain=1#L4 both specify that the required WP version is 4.0.

If we make the proposed change, we'll need to bump this minimum. Ideally we'd be able to see what proportion of plugin users are using versions 4.0 to 4.4, but the tracking hasn't yet been setup, so making this change will mean potentially dropping some users from future updates. For the sake of having an extra wrapping function, it doesn't seem worth the hassle at this stage; there will be a lot of other changes to make once WP and PHP versions are bumped.

**Comment by pauarge** [comment]
I see your point. My point was coming from the fact that it's a very old WordPress version and the bump from 4.0 to 4.4 as a required minimum doesn't look to me as a big one. However, since we don't have metrics for it, we can play it safe and don't bump it.

I would say let's leave this issue open for when we raise the minimum WP we remember to get rid of the wrapper.

**Comment by GaryJones** [comment]
Closed in #417.
