### ISSUE TITLE
Filter $parselyPage variable.

### ISSUE THREAD

**Issue by scottnelle** [Parsely/wp-parsely#39]
It would be super handy if we could filter `$parselyPage` right before output. I'm specifically interested in being able to add the metadata field outlined here https://www.parsely.com/help/integration/jsonld/ but a general filter would be ok by me.

**Comment by hbbtstar** [comment]
hi Scott!

It definitely wold be, and there are a couple of PRs out looking to do the same thing (https://github.com/Parsely/wp-parsely/pull/32 and https://github.com/Parsely/wp-parsely/pull/23). We're going to get it into the next version update along with some other fixes, hopefully soon! 

cc @jtotoole

**Comment by jtotoole** [comment]
Closed via https://github.com/Parsely/wp-parsely/pull/50
