### ISSUE TITLE
Add testing on the recommended widget

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#399]
## Is your feature request related to a problem?

The recommended widget fetches the data and renders completely on the client side through Javascript. That Javascript is self contained and built through Webpack, but it doesn't have any testing. 

We also don't have testing on the PHP side. Some integration tests around how data is managed and updated for the plugin options would be helpful.

## Describe the solution you'd like

We'd like to add Jest-based unit tests (similar to `personalization.test.js`) plus E2E tests (similar to `activation-flow.spec.js`) that cover the front-end part of the widget.

To cover the back-end part, we would want PHP integration tests.

## Additional context

We could also consider adding testing to cover this widget on the WordPress (PHP) side, basically regarding the admin panel.

**Comment by jblz** [comment]
See #545 -- the widget was broken and this sort of test would have caught it.

**Comment by acicovic** [comment]
We are planning on removing the Widget in wp-parsely 4.0.0. I'm unsure we would write tests for a feature that is to be removed, so we should see if this ticket is still relevant.

**Comment by pauarge** [comment]
We are safe to close this. The recommended widget is in maintenance mode right now and it will be deprecated.
