### ISSUE TITLE
Test the plugin against multiple WordPress versions

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#407]
## Is your feature request related to a problem?

Currently we only test the plugin in our CI tests against a single WordPress version. That is in contrast to PHP, for which we test against a matrix of different versions.

## Describe the solution you'd like

We'd like to test multiple WordPress versions. According to the article below, we should set a lower limit on WP 5.2. We can set up these different WP versions on GitHub Actions and require all versions to pass before a PR can be accepted.

A good inspiration on how to test different WordPress versions in CI might be `vip-go-mu-plugins`: https://github.com/Automattic/vip-go-mu-plugins/

## Additional context

https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/

**Comment by GaryJones** [comment]
`e2e-tests.yml` and `integration-tests.yml` will need updating - the other workflows aren't dependent on WordPress.
