### ISSUE TITLE
Move CI images to Ubuntu 20.04

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#413]
## Is your feature request related to a problem?

We are currently using `ubuntu-18.04` images in our GitHub Actions, due to MySQL 8 and old PHP compatibility issues. We should use more up to date system images.

## Describe the solution you'd like

Update those images to use `ubuntu-20.04`. We'll be able to upgrade once the minimum PHP required version is 7.1.

**Comment by GaryJones** [comment]
Might need PHP 7.4: https://www.php.net/manual/en/mysqli.requirements.php

**Comment by pauarge** [comment]
As @GaryJones mentions, our pipelines fail with PHP versions lower than 7.4: https://github.com/Parsely/wp-parsely/pull/445

I have closed that PR, but it can be reused in the future if we decide to upgrade our minimum PHP requirements. At the same time, I'm pushing this issue to further milestones.
