### ISSUE TITLE
Check compatibility with WordPress 4.6

### ISSUE THREAD

**Issue by jtotoole** [Parsely/wp-parsely#43]
Got this email today -- new WordPress version comes out August 16th, so I guess we can test locally at that point and then update our ReadME? The field guide they link to will be a solid resource to peruse to gauge whether there are any changes that could affect this plugin.

--

WordPress 4.6 is scheduled to be released on 16 August 2016. Are your plugins ready?

After testing your plugins and ensuring compatibility, it only takes a few moments to change the readme "Tested up to:" value to 4.6. This information provides peace of mind to users and helps encourage them to update to the latest version.

Here are the current "Tested up to:" values for each of your plugins:

 * https://wordpress.org/plugins/wp-parsely/ (tested up to 4.5)

For each plugin that is compatible, you don't need to release a new version -- just change the stable version's readme value.

Looking to get more familiar with 4.6? Read this roundup post on the core development blog to check out the changes made to register_meta(), native fonts, persistent comment cache, Customizer APIs, WP_HTTP API, and much, much more: https://make.wordpress.org/core/2016/07/26/wordpress-4-6-field-guide/

**Comment by jtotoole** [comment]
This new version is working locally for me. @hbbtstar, is compatibility with the new version something we can/should incorporate with the Travis build?

**Comment by hbbtstar** [comment]
yup, travis is already set to test against latest automatically. I bumped our tested to number in readme.txt and I'll close this one out!
