### ISSUE TITLE
Move Javascript code to TypeScript

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#471]
## Is your feature request related to a problem?

Currently we don't type check our Javascript codebase (we do for the PHP side). This leads to more bug-prone code. 

## Describe the solution you'd like

We could move the Javascript files to TypeScript. Since we're using built code already, adding an additional step that transpiles TS to JS wouldn't be much of an issue.

## Describe alternatives you've considered

Not type check the JS code because it's relatively small, anyway. This might be valid now, but it the future it will probably grow on size.

**Comment by jimmywarting** [comment]
you can have type safety without typescript syntax if you use jsdoc... most time you don't even have to annotate your code if you do it right

Imo typescript only slows down the development processes, you will just spend more time upfront.
...Deno removed typescript
...esm + typescript is no good at the moment, its a #developerPain
