### ISSUE TITLE
Settings page: Improve UI for post/page types to track

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#483]
## Is your feature request related to a problem?

We don't want users to track posts and page types twice. Right now, the UI lets them do that and we'd like to not allow them.

## Describe the solution you'd like

@GaryJones describes a good solution here: https://github.com/Parsely/wp-parsely/pull/482#issuecomment-963287549

**Comment by acicovic** [comment]
This is a comment is from @GaryJones and was posted [here](https://github.com/Parsely/wp-parsely/pull/482#issuecomment-963287549). I'm including the comment here for reference and ease of use:

> * Can we use JS (and back-end validation) to disable checkboxes when it has already been marked in the other type?
> 
> * Alternatively, I wonder whether radio buttons would help enforce this better (shown as a table here, but really fieldset rows, one row for each viable post_type) since what we really want is for each type to be assigned to exactly one of either `post`, `page` or `none`:
> 
> 
> |   | None | Post |  Page |
> | --- | :---: | :---: | :---: |
> | post  | o | ⦻ | o |
> | page  | o | o | ⦻ |
> | attachment  | ⦻ | o | o |

**Comment by acicovic** [comment]
I would love to get feedback from the others. Here's my take:

> Can we use JS (and back-end validation) to disable checkboxes when it has already been marked in the other type?

Back-end validation is being worked on (see #543). JS validation implementation will depend on the solution we decide to implement.

> Alternatively, I wonder whether radio buttons would help enforce this better...

This makes sense to me personally. Else, in the case of checkboxes we could just implement an auto-uncheck JS function.

**Comment by GaryJones** [comment]
> we could just implement an auto-uncheck JS function

That's assuming that JS is enabled - and we can get the same benefit by using native HTML.

**Comment by pauarge** [comment]
+1 on implementing this without JS, just with native HTML.

**Comment by acicovic** [comment]
Given that most of us seem to agree with the radio solution, I'll take note of this and look into it.

In the meantime, don't hesitate to provide any other feedback.
