### ISSUE TITLE
Clean up settings page class

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#485]
## Is your feature request related to a problem?

The settings page class (`class-settings-page.php`) contains some repeated logic for rendering fields, and it's missing some checks that might lead to a broken layout. The page works, but the code is smelly and some changes on it might break the page easily.

## Describe the solution you'd like

We should simplify the methods and extract common behavior into helper functions. See comments below.

## Describe alternatives you've considered

Don't touch anything as it's technically not in a broken state right now.

## Additional context

This has been discussed in https://github.com/Parsely/wp-parsely/pull/482#discussion_r745389969 and https://github.com/Parsely/wp-parsely/pull/482#discussion_r745393411.

**Comment by GaryJones** [comment]
I actually started a little on this on the weekend but bit off too much, and started following https://carlalexander.ca/designing-class-wordpress-admin-page/ to at least move some markup-heavy code into views. Not saying this whole article is what we should aim for, but certainly there are ways to cut the class down in length.

**Comment by acicovic** [comment]
Note to our future selves: In the above merged #531 PR, @GaryJones has noted some improvements to be made to the code. The respective comments can be found easily as they are the 3 comments that are not marked as outdated.

**Comment by acicovic** [comment]
Notes from #531:
- https://github.com/Parsely/wp-parsely/pull/531#discussion_r796513470 (this would also apply to other parts of our code that use `empty()`. 
- https://github.com/Parsely/wp-parsely/pull/531#discussion_r796514163
- https://github.com/Parsely/wp-parsely/pull/531#discussion_r796515607

Notes from #766:
- https://github.com/Parsely/wp-parsely/pull/766#discussion_r848546763

**Comment by mehmoodak** [comment]
It seems like we already have the needed helper functions in place like:

- `print_filter_text`
- `print_description_text`
- `print_text_tag`
- `print_checkbox_tag`
- `print_select_tag`
- `print_radio_tags`
- `print_media_single_image`

So this issue can be closed. Please do let me know if anyone have concerns otherwise will close it in next 2 days.

**Comment by acicovic** [comment]
I took a quick look into the setting's page code.

It is a big file, but the code seems structured well-enough. There are always further opportunities for improvement, but we can open those as specific issues if needed. There are also other open issues that will probably result in further changes/restructuring to that file.

So @mehmoodak, feel free to close this.

**Comment by danielabloch** [comment]
Closing this, per the last 2 comments.
