### ISSUE TITLE
Idea: Add Screen Options to toggle visibility of Requires Recrawl and Advanced Settings

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#520]
## Is your feature request related to a problem?
Even with the refactored UI from #518, the settings page can still appear daunting, with a lot of options.

## Describe the solution you'd like
We could add a Screen Option that enables the display of the Requires Recrawl, and Advanced Sections. This not only makes it an extra step to do something potentially destructive (though fixable), it also can reduce the number of visible settings for those who don't need it.

## Describe alternatives you've considered
Displaying each section as a Tab, which provides a little more discoverability than a screen option.

## Additional context
We could even combine the Tabs and screen options ideas together.

**Comment by acicovic** [comment]
This has been implemented in #531 so I think we can close this issue (if we consider tabs, we should probably open another issue).
