### ISSUE TITLE
Update screenshot for settings page

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#553]
3.1.0 of the plugin organised the settings page into new sections.
#552 fixed some strings on the settings page.

We should update `.wordpress-org/screenshot-1.png` to show the new settings page look (but hack locally to show the version as `3.1.0` first!).

**Comment by acicovic** [comment]
Should we go for the whole settings page or just a part of it?

**Comment by GaryJones** [comment]
Whatever makes most sense is fine with me - could even have multiple screenshots for the new different sections.

**Comment by pauarge** [comment]
I would go for multiple screenshots, they are easier to understand.

**Comment by acicovic** [comment]
So here's the screenshot I'm planning to use as a base:

![image](https://user-images.githubusercontent.com/23142906/147928050-d94d3280-4657-422e-9557-bd9e36638d67.png)

My suggestions:
- Remove plugin version number so the screenshot doesn't look outdated in a few releases. Whenever UI gets updated, screenshots will be updated respectively anyway.
- Break the screenshot in 2 or 3 pieces based on its sections (1 = Basic Settings, 2 = Requires Recrawl Settings, 3 = Advanced settings or 1 = Basic Settings, 2 = Requires Recrawl Settings + Advanced settings).

Any preferences?

**Comment by pauarge** [comment]
The screenshot looks good to me. I would break it in three sections as you suggest.
