### ISSUE TITLE
Last Modified date is wrong in the json+ld

### ISSUE THREAD

**Issue by SandowMichaelMa** [Parsely/wp-parsely#558]
## Describe the bug
The last modified date in the json+ld output by the parsely plugin is wrong. It always outputs the created date due to the if statement.

On: 
https://github.com/Parsely/wp-parsely/blob/7c372ca9e26bb3c0af14d2b81af355644ed2cea3/src/class-parsely.php#L452
https://github.com/Parsely/wp-parsely/blob/7c372ca9e26bb3c0af14d2b81af355644ed2cea3/src/class-parsely.php#L453

The function code is using: get_the_modified_date( 'U', true )

The documentation: https://developer.wordpress.org/reference/functions/get_the_modified_date/ says that the second argument should be post object or post ID. Using true returns a bad value. Changing true to $post should fix the issue although will probably not be in GMT time.

Given the code, I'm assuming you probably meant to use: get_post_modified_time  
https://developer.wordpress.org/reference/functions/get_post_modified_time/

In which case swapping out the functions would work fine with the original code (although still probably should explicitly pass in the $post object for the third argument).

## To Reproduce
Go to any page with parsely plugin enabled and the view the json+ld data.

## Expected behaviour
Returns the last modified date of the post.

**Comment by GaryJones** [comment]
@SandowMichaelMa Thank you for your great bug report 😍. Looks like a good catch! 

While the fix looks simple, we'll aim to spend a bit of time working on having tests for this to avoid this issue happening again in the future.

**Comment by acicovic** [comment]
Yes, I'll be looking into this. In my case, this issue wasn't being triggered in my development environment which might explain why this was not caught earlier.

**Comment by pauarge** [comment]
Thanks @SandowMichaelMa for catching this! 

Since this a bug that's affecting customers today and we have a working solution, I think we should push for a bugfix release before 3.1.0. Once we have the tests in place, we can cherry-pick the commit and do a release with just that.
