### ISSUE TITLE
Proposal: Reduce 'magic strings'

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#563]
## Description

Browsing through the plugin code, I see that certain elements could use a conversion from a 'magic string' to a constant value.

Notable candidates for this are strings that may be used many times and in multiple places. For example filter names and setting keys, strings that we would like to share with other parts of the code (for example tests), or strings that are prone to be misspelled like the below date formatting strings:

https://github.com/Parsely/wp-parsely/blob/501a7e5f7410206d62b9126883ff0622b76939b3/src/class-parsely.php#L450-L457

## Example

I expect that most of those strings live within the main `Parsely` class, and I would expose them as public constants so they can also be used by external code. For example:

```php
class Parsely {

    // Option keys start with OPTIONS_KEY_
    public const OPTIONS_KEY_LOGO = 'logo';

    // Filter names start with FILTER_
    public const FILTER_SKIP_PASSWORD_CHECK = 'wp_parsely_skip_post_password_check';
    public const FILTER_EMPTY_NOT_STRING_FROM_ARRAY = 'filter_empty_and_not_string_from_array';

    // Other miscellaneous strings can start with STRING_ or STR_
    public const STRING_DATE_FORMAT_DEFAULT = 'Y-m-d\TH:i:s\Z'
```

## Advantages (and disadvantages?)

For me, the main reasons to go forward with this would be improved maintainability, reduced chances of making mistakes as well as code auto-completion. If we would like to go forward with this, it would be better to do it now while our codebase is still small.

The only possible downside would be a "too crowded" constant declaration section. However, when this happens it can often be sign that a class must become multiple classes. For example, if we get to have too many `OPTIONS_KEY_*` constant declarations within the `Parsely` class, this may mean that it's time to create an `Options` class and move the constants as well as options-related functionality there.

## Request for feedback from contributors

Contributors, let me know whether this makes sense to you and if you have any comments, objections or feedback about this. If we agree that these changes are a step towards the correct direction, I'll be happy to work on this.

Thanks!

**Comment by GaryJones** [comment]
+1000000 for pulling more classes out of Parsely\Parsely, before even thinking about creating strings as constants. 

If a string isn't used in multiple places, then constants aren't needed; adding them in makes the code harder to read, and at the end of the day, a (sufficiently unique) string can be easily replaced en masse from a maintenance perspective.

**Comment by acicovic** [comment]
I'm all for extracting classes, though I'll post this in another thread to keep this one on topic.

**Comment by pauarge** [comment]
I really like this issue and we should definitely pursue it as an engineering health task in the future.

**Comment by acicovic** [comment]
Note: the string 'wp-parsely' is being used everywhere as the text domain. This should probably be converted to a constant.

**Comment by GaryJones** [comment]
> Note: the string 'wp-parsely' is being used everywhere as the text domain. This should probably be converted to a constant.

No, it shouldn't. https://pascalbirchler.com/text-domain-wordpress-internationalization/#string-extraction

Specifically, the tools that read and extract the strings, are effectively using a tokenizer approach, and it's not a situation where the PHP has been run - a constant defined elsewhere (same or another file) won't resolve to a string.

**Comment by acicovic** [comment]
> No, it shouldn't. https://pascalbirchler.com/text-domain-wordpress-internationalization/#string-extraction

Yes, I experimented with this earlier today but IntelliSense complained. So it won't be done.

**Comment by acicovic** [comment]
Closing this issue as too generic and as part of #564, as well as this being a practice that will be done for any new code or when refactoring any existing code.
