### ISSUE TITLE
Proposal: Extract classes from main Parsely class

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#564]
## Description
In an ideal world, each class should have a specific responsibility, encapsulate it and expose members so other classes can use the functionality. The `Parsely` class still seems to have several responsibilities that could be extracted as external classes. This would improve code quality and simplify the main class.

Here are the ones I can think off the top of my head:

- A currently obvious one is `Metadata` as the `construct_parsely_metadata()` function is very long and (IMO) should be broken into sub-functions. I would propose the creation of a `Metadata` (or similarly named) class that would include this function and all its sub-functions, as well as any other metadata-related functionality of course.
- Another one that could be discussed is `Options`. This is a more complicated one as we're getting options in many places in different ways (haven't looked at this in detail).

## Next steps

1. Discuss and decide if we want to go forward with this idea
2. Propose/determine the extractions that would be useful
3. Determine the cost/implications of each possible extraction, as to decide if we should go forward with implementation (for example, is it simple? Will it require a lot of refactoring in the `Parsely` or other classes? Is the effort worth it?). Something to always keep in mind that the plugin is still small and that it's better to do expensive operations now, instead of possibly regretting it in the future.
4. Implement the good ones
5. Profit!

## Request for feedback from contributors

So here it is. Contributors, let me know of your comments, objections or feedback about this. I'll be happy to work on this, provided we decide what to extract. Please make your comments and propositions so we can determine the most useful extractions.

Thanks!

**Comment by acicovic** [comment]
Related: #323

**Comment by GaryJones** [comment]
> A currently obvious one is Metadata as the construct_parsely_metadata() function is very long and (IMO) should be broken into sub-functions. I would propose the creation of a Metadata (or similarly named) class that would include this function and all its sub-functions, as well as any other metadata-related functionality of course.

I would take this further - one class that handles the logic of getting the right values for the context, and two other polymorphic classes for the different outputs (JSON, repeated metas). Use a [polymorphism refactor](https://refactoring.guru/replace-conditional-with-polymorphism) to replace [this conditional](https://github.com/Parsely/wp-parsely/blob/501a7e5f7410206d62b9126883ff0622b76939b3/src/class-parsely.php#L198-L226).

Furthermore, the construction of metadata right now is adding values to things like `$metadata['dateCreated']` and `$metadata['dateModified']` - how about if different classes existed that contained just the properties that each context (post vs page vs term archive vs homepage vs author page vs...) needed? It would be Polymorphism in action again.

> Another one that could be discussed is Options. This is a more complicated one as we're getting options in many places in different ways

I would also extract a `Validator` class out of the `Options` class as well, and pass it back into `Options` via an injected dependency - this would also allow for it to be mocked for testing, and for `Validator` to be unit tested without having to fire up WP.

Others:

- These ["update Parsely" methods](https://github.com/Parsely/wp-parsely/blob/501a7e5f7410206d62b9126883ff0622b76939b3/src/class-parsely.php#L501-L591) seem like they should go into their own class as well.
- `get_tags(), `get_cats()`, and `post_has_trackable_status()` are all finding properties of a Post - seems like we could use composition and a Decorator pattern to create our own object with wraps WP_Post extra data and use that everywhere where these extra data is needed.
- As per [this comment](https://github.com/Parsely/wp-parsely/pull/510#pullrequestreview-816638786), the Co-Authors Plus class should be able to be pulled out and loaded / applied conditionally.
- Anything like `VERSION` and similar constants, can be moved to a `Parsely\Plugin` class - it's named more specific than just a `Parsely` class.

**Comment by pauarge** [comment]
+1 on extracting classes. We did a fair amount of it on the 3.0 release, and as @GaryJones and @acicovic point out there is plenty of room for improvement. 

We should tackle this in the next major release. The reasoning behind it is that there are many customers calling methods on `class-parsely` directly, which is not ideal. When we go through this, we should keep that in mind and mark methods that will be moved as deprecated if necessary.

**Comment by acicovic** [comment]
Also see #682 about restructuring metadata.

**Comment by mehmoodak** [comment]
The actual ask of moving `construct_parsely_metadata` to its own class has been done so I think we should close the ticket based on following points.

1. This ticket is inactive for 10 months now.
2. Our class-parsely.php file is not just 480 lines long.

Please share your concerns if any else we will close the ticket in next 2 days. Thanks

**Comment by acicovic** [comment]
I agree that this ticket has been inactive for some time and that the file is not particularly long. Also, the title of the issue is generic, and what it says has been done to a certain extent.

Having said that, I think that some points made in the thread could still be valid, and that there is still room for improvement in that specific class. I think it is also a good reminder for us to avoid adding things there without careful consideration, since it could become quickly a big catch-all file.

I will not object to closing this. At the same time, I do think that if there is something useful left in this issue, we could consider it and post it as a more-specific and actionable issue or issues. At the same time, we should avoid micro-optimizing too much as it can become counter-productive. So there is definitely a balance to be kept. I think that this is valid not only for this specific issue, but for any issue that we consider closing.
