### ISSUE TITLE
Plugin not handling "&" properly in creating section value

### ISSUE THREAD

**Issue by evantwidwell** [Parsely/wp-parsely#573]
Parsely plugin user Stanford Daily reports issue where section value pulled from WP is being oddly changed in the JSON-ld created for their site. When category "Business & Technology" is used as primary category it is being added as articleSection in the JSON-LD as "Business &amp; Technology" See screenshots of WP CMS values and JSON-LD the plug in is producing.

![image](https://user-images.githubusercontent.com/59800349/147982970-7a09a2b0-b1d7-43e7-8052-d38c28d97797.png)

![image](https://user-images.githubusercontent.com/59800349/147982838-4abaada0-9bc1-41b2-8cb9-7baf2905688f.png)

## Expected behaviour
The expected behavior would be for the Plugin to create the JSON-LD with the values exactly as they are in the CMS

Thank you and let me know if there's more I can do to help here.

**Comment by jblz** [comment]
Hi, @evantwidwell.  

Thanks very much for the report.  I _think_ inclusion of HTML entities such as this should be ok as far as the metadata are concerned per this spec:
https://www.w3.org/TR/json-ld11/#restrictions-for-contents-of-json-ld-script-elements

I _do_ understand that we may be incorrectly representing this in the Parsely dashboard with the HTML entities unencoded.  I'll leave this issue open here until we can verify that we can fix this outside this codebase.

Thanks again!

discussion: p1641248046000500-slack-C01MHPS2T4J

**Comment by pauarge** [comment]
Hello again @evantwidwell. 

We have tracked down the issue and the WordPress plugin is behaving correctly, as Jeff points out above. We have an issue when rendering that character on the Parse.ly dashboard. We have notified the team and they are working on a fix. I'm closing this issue because we don't expect to perform any changes on the plugin.

Thanks for reporting!

**Comment by evantwidwell** [comment]
Thank you for following up and for investigating @pauarge and @jblz!
