### ISSUE TITLE
Support Network Installation

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#575]
## Is your feature request related to a problem?
https://www.parse.ly/help/integration/wordpress mentions that:

> Installation of the Parse.ly WordPress plugin must be done individually per site. A network install will not work because each site needs to specify the site ID.

We should make handling that task as simple as possible, so that it can be network activated successfully.

## Describe the solution you'd like
@jblz says that a simple network enable / site ID setting UI would be super straightforward.

We might also consider providing a solution or documentation on how someone can use a pre-defined set of non-default settings across all subsites (other than than the known-to-be-unique apikey and API secret).

## Describe alternatives you've considered
We could do nothing and not support network installation, but that hinders adoption - considers customer applications with hundreds of subsites, and the pain there would be in activating them and configuring them individually (even with bash scripting with WP-CLI).

## Additional context
We only have one integration test that requires multisite.

**Comment by pauarge** [comment]
Let's make sure we update the documentation on the Parse.ly side to reflect that we support the network installation.

**Comment by GaryJones** [comment]
Other ideas, include having a Network admin page with a table of subsites with links to the Parse.ly Settings page for each subsite. This could later be enhanced with "quick edit" text fields to enter the apikey directly on this network admin page.

**Comment by pauarge** [comment]
Worth checking:

- https://codex.wordpress.org/Creating_Options_Pages
- https://codex.wordpress.org/Settings_API

**Comment by pauarge** [comment]
Development work on this has been finished in the PR above. We should update our documentation accordingly.
