### ISSUE TITLE
Front-end scripts not loading after plugin update

### ISSUE THREAD

**Issue by timbolimboslice** [Parsely/wp-parsely#580]
## Describe the bug
We recently tried updating our plugin from version 2.5.0 to 3.0.2. However, after updating, I'm noticing that the `wp-parsely-api` and `wp-parsely-tracker` are not appearing on the front-end. I stepped through `class-scripts.php` and they appear to be enqueuing as expected. This was using WordPress version 5.7, however, even after updating to 5.8.2, the problem still exists.

We would like to update to the most recent version, please let me know how I can help assist.

**Comment by jblz** [comment]
Hi, @timbolimboslice.  Thanks for the report.  Let's see if we can get to the bottom of it.

Per [the loading method, `Scripts::run`](https://github.com/Parsely/wp-parsely/blob/77d032037d00624600e823f516880f10b16ea7a2/src/class-scripts.php#L44-L46), the plugin:
1. Registers both scripts in the `init` action with the `$in_footer` parameter set to `true`
2. Enqueues the `wp-parsely-api` script in the `wp_enqueue_scripts` action 
3. Also Enqueues the `wp-parsely-tracker` script in the `wp_enqueue_scripts` action

Looking at [what's changed between those versions](https://github.com/Parsely/wp-parsely/compare/2.5.0...3.0.2), we now rely on `wp_enqueue_scripts` being called where we hadn't prior, but that doesn't seem to be the issue if you're seeing the scripts enqueued on your end.

As before, this relies on the `wp_footer` action being called by the theme to actually print the `<script />` tags. Is there a chance it's not getting called?

I'm still looking into it on my end, but please let us know if you run across anything else that might help diagnose.

Cheers.

**Comment by GaryJones** [comment]
@timbolimboslice Do you have custom code which uses any wp-parsely filters?
Do you have any custom code which references classes from the plugin by name? (Many were put into namespaces in 3.0)
Can you try the wp-parsely 2.6.1 release temporarily, and see what happens with that version? That will help to narrow down what the critical change is.

**Comment by timbolimboslice** [comment]
@jblz @GaryJones  Thank you both for your quick responses. I went ahead and installed `2.6.1` and scripts were still rendering correctly. I updated to `3.0.2` and took another look with fresh eyes and found out that the issue was in the theme on our end. All scripts are loading as expected now. 

Thanks for your help!

**Comment by acicovic** [comment]
Hi @timbolimboslice, thank you for getting back to us!
