### ISSUE TITLE
Reorganize wp-parsely.php and tackle autoloading issues

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#586]
## Is your feature request related to a problem?

During the past few months, we have put a significant effort into splitting the plugin's logic into smaller files and classes. That has lead to the plugin's base file, `wp-parsely.php`, growing quite a bit in size. The file has multiple repeated hooks and a mixture of lambda and named functions. It also handles all the `require` of the plugin (except for tests).

## Describe the solution you'd like

- We'd like a file that is leaner, cleaner, and easier to maintain. 
- We would like to reduce the number of hooks that we use and have a unified decision on whether all hooks are lambdas or named functions. 
- We'd like to solve the autoloading issues, especially with tests.

## Describe alternatives you've considered

@jblz did some exploration with this topic https://github.com/Parsely/wp-parsely/pull/556

## Additional context

We'd like to prevent things like this from happening: https://github.com/Parsely/wp-parsely/pull/569#discussion_r781180713

**Comment by GaryJones** [comment]
I could get behind the structure described at https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md

Among other things, it suggests using a config class (like [this](https://github.com/szepeviktor/small-project/blob/master/src/Config.php)) to replace global (namespaced) constants - big +1 for that.
