### ISSUE TITLE
Fatal TypeError reported in get_categories function

### ISSUE THREAD

**Issue by jblz** [Parsely/wp-parsely#587]
## Describe the bug

We have received a report from a customer. When they attempt to upgrade to version 3.0.2, they are met with an error:

`explode() expects parameter 2 to be string, bool given in ... src/class-parsely.php:675`

Per logs, the function was called thusly:

`explode( '/', false )`

Here's the pertinent line:

https://github.com/Parsely/wp-parsely/blob/77d032037d00624600e823f516880f10b16ea7a2/src/class-parsely.php#L675

The customer also added context:

> The posts (namely, links to posts) stopped working when navigating from the Home page. The archive pages worked correctly, and the posts opened correctly when accessing from the archive pages, but not from the Home page.

## To Reproduce

No fatals.
Links present, correct, & functioning.

## Additional context

140584-zd-wordpressvip
p1641908716117600-slack-C011HP930Q7

**Comment by arhine** [comment]
The customer also added this note:

> Regarding the question on the version we had installed:
> 
> We upgraded to 3.0.2, noticed an error on all post related pages, and reverted to 2.6.1
> On versions 3.0.1 and 3.0.0, the error also exists.
