### ISSUE TITLE
report of fatal error in Parse.ly plugin version 3.0.3

### ISSUE THREAD

**Issue by LauraKalnicky** [Parsely/wp-parsely#594]
VIP gold agency partner Rareview is implementing Parse.ly. Today they sent us this error:

> I'm getting PHP Fatal Errors when trying to Network Activate Parse.ly plugin (3.0.3) on our Rareview.com staging site (stage.rareview.com). The staging site is currently running WordPress Version 5.9-RC2-52567. 
> 
> Here is error output:
> 
> Fatal error: Cannot declare class Parsely\UI\Plugins_Actions, because the name is already in use in /var/www/wp-content/plugins/wp-parsely/src/UI/class-plugins-actions.php on line 22
> 
> [stage.rareview.com/wp-admin/plugins.php?action=error_scrape&plugin=wp-parsely%2Fwp-parsely.php&_wpnonce=0cc71346ef]
> 
> Please advise. Thanks!

**Comment by pauarge** [comment]
Hi @LauraKalnicky. Could we suggest that the customer checks if they have two installations of the plugin?

**Comment by pauarge** [comment]
Closing because this is an error with the customer's set up, not the plugin itself.

**Comment by colorful-tones** [comment]
@pauarge @LauraKalnicky as far as we're aware there is not two active Parse.ly plugins. Only one plugin being installed and activated. Please re-open and advise. Thanks!

**Comment by colorful-tones** [comment]
_Actually_, I take that back. It seems that VIP's [`mu-plugins`](https://github.com/Automattic/vip-go-mu-plugins/) already include [a copy of Parse.ly](https://github.com/Automattic/vip-go-mu-plugins/tree/master/vip-parsely). Can you folks please provide documentation on how to work with that version of Parse.ly please?

**Comment by pauarge** [comment]
Hi @colorful-tones. You should get rid of the Parse.ly version that you have on your client plugins and enable the provided version by adding the following snippet somewhere in your code (for instance, `plugin-loader.php`):

```
add_filter( 'wpvip_parsely_load_mu', '__return_true' );
```

**Comment by GaryJones** [comment]
There are a few docs at: https://docs.wpvip.com/technical-references/plugins/parse-ly/

**Comment by colorful-tones** [comment]
Awesome, thanks @pauarge @GaryJones 👍
