### ISSUE TITLE
Improve plugin page on wordpress.org

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#609]
## Is your feature request related to a problem?
Our [wordpress.org plugin page](https://wordpress.org/plugins/wp-parsely/) could use some love. For example, as a beginning we could add more tags and fix the page's current display problems. Also, it seems that the plugin page doesn't completely obey to our README.md (for example, we do have extra tags in our README.md). Our plugin page is our interface with the world, so we should be able to manipulate it as best as possible.

## Describe the solution you'd like
Create a readme.txt file to be able to control the plugin's page contents. My understanding is that this will also allow us to have a different readme for the plugin's page and another one for this repository (which is be default the README.md).

Related material:
- [readme.txt documentation](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/).
- The [readme.txt from Yoast](https://github.com/Yoast/wordpress-seo/blob/trunk/readme.txt) can be used as a reference as it contains everything (screenshots, FAQs, code blocks) and I think it powers everything in [their plugin page](https://wordpress.org/plugins/wordpress-seo/).

**Comment by pauarge** [comment]
Noting that the broken syntax will be fixed with the release of 3.1.0.

**Comment by acicovic** [comment]
OK, so we may need to see if it does make sense to go towards a readme.txt file. No need to do it if we the README.md is enough.

**Comment by acicovic** [comment]
I've been informed by @GaryJones that having a single README.md file is intentional in order to avoid documentation duplication.

This should be OK, since we now have many different documentation files and we can move things from the main readme to other places if needed (which is already the case for the "Local Development" section for example).

Having said that, our [wp.org page](https://wordpress.org/plugins/wp-parsely/) still seems broken after the 3.1 release.

**Comment by acicovic** [comment]
Here are some thing we can work on (will keep updating as I spot issues):
- [x] Fix broken code blocks.
- [x] Make all tags show.
> **Update:** Only some tags are shown, and this is a default behavior.
- [x] The "parsely" contributor has a person picture. I think a logo picture would make more sense for that.
> **Update:** @hbbtstar has been informed and is taking care of this.
- [x] Check what needs to be done to show that the plugin provides a block.
> **Update:** We don't provide a block yet, but we will soon. Using `block.json` would be the best way to go.
- [x] New screenshots of the plugin settings page are needed, as some of the latest PRs introduce new interface elements there.

**Comment by GaryJones** [comment]
> Make all tags show.

The displaying of tags appears to be selective - perhaps related to the closeness to the plugin slug, or recognised as a trademarked company name. Added a new tag in the PR, and it appeared fine.

> The "parsely" contributor has a person picture. I think a logo picture would make more sense for that.

Have asked @hbbtstar to take care of that with instructions of what's needed.

**Comment by acicovic** [comment]
> > The "parsely" contributor has a person picture. I think a logo picture would make more sense for that.
> 
> Have asked @hbbtstar to take care of that with instructions of what's needed.

Had asked @hbbtstar if we could change the picture and he had said yes, but what you propose is more thorough.
