### ISSUE TITLE
Consider adding a built admin JS file

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#617]
## Background
in #518, the [build/admin-page.js](https://github.com/Parsely/wp-parsely/pull/518/files#diff-42362a4f044a00cc6e4da9c8818d0285d91131efcbd0f08e3572d02752291223) file was removed.

However, in #570, a new `src/js/admin/index.js` file was introduced and @jblz commented:

> I think we should reinstate the built admin page js file that was removed in #518 to keep consistency with the rest of the scripts and provide the expectation of a common runtime when working in JS.
>
> That would make it fairly straightforward to use the [MediaUpload](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-media-utils/#mediaupload) component ([usage](https://github.com/WordPress/gutenberg/blob/9675b99c6e7c88af16749acc3dd0dcdfbe35db27/packages/block-editor/src/components/media-upload/README.md)).

## Goal of this issue
The goal of this issue is to capture any related discussion here and decide whether we should go forward with this.

**Comment by acicovic** [comment]
Since @pauarge has expressed that built-in styles should be avoided, adding here as a sidenote that in the future we might also need to introduce an admin CSS file. For example, #483 might need some CSS. Also adding tabs like mentioned in #520 would need to introduce at least some amount of CSS.

**Comment by jblz** [comment]
For now, I think we can hold off on refactoring to use MediaUpload, etc. as it will add significant complexity for a single control, but I still think it's worth building our scripts in a consistent manner.
