### ISSUE TITLE
Move some .md files into a docs directory

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#621]
## Is your feature request related to a problem?
Our project has now multiple .md files like:
- README.md
- CHANGELOG.md
- CONTRIBUTING.md
- WINDOWS.md
- README.md (in `tests/e2e`)

## Describe the solution you'd like
We should perhaps consider grouping some of these files into a docs (or similarly-named) directory. Are there any opinions on how this should be done?

**Comment by GaryJones** [comment]
GitHub will do certain things with certain files if they exist in certain places :-)

**Comment by acicovic** [comment]
OK, noted.

**Comment by acicovic** [comment]
According to the documentation I could find, we could move everything into a `docs` directory. Even by doing so, the `README.md` should be visible in our repo page. In general, there seem to be three places where GitHub will take into account such files: The repo's root folder, the `.github` folder and finally the `docs` folder.

Personally I would choose the `docs` folder in our case. My only question at this point would be what we would like to do with the `README.md` in the `tests/e2e` directory. @pauarge, any preferences?

Related tidbits:
> If you put your README file in your repository's root, docs, or hidden .github directory, GitHub will recognize and automatically surface your README to repository visitors.

> Decide whether to store your contributing guidelines in your repository's root, docs, or .github directory.

> If a repository contains more than one CONTRIBUTING file, then the file shown in links is chosen from locations in the following order: the .github directory, then the repository's root directory, and finally the docs directory.

Sources:
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by GaryJones** [comment]
Leave README.md in the root, as that's where it needs to be for the WordPress.org SVN anyway.

I'd say leave the tests Readme where it is as well, as it's contextual to running the tests.

**Comment by acicovic** [comment]
Good points.

**Comment by acicovic** [comment]
I'll also leave CHANGELOG.md outside the docs directory since it isn't really docs, but we can change this later in the PR if we finally decide to move it.

**Comment by acicovic** [comment]
Closing this issue after feedback on the PR which resulted in its closure.
