### ISSUE TITLE
Some integration tests may fail on Windows due to line feed differences

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#630]
## Describe the bug
Some integration tests may fail on Windows due to line feed differences.

## To Reproduce
1. Run integration tests on Windows
2. See tests output

## Expected behaviour
Integration tests should pass.

## Screenshots
![image](https://user-images.githubusercontent.com/23142906/151519694-acd6ef89-2cf2-4b8a-9ef6-3e1040298ee3.png)

**Comment by GaryJones** [comment]
Would `PHP_EOL` instead of `\n` help here?

**Comment by acicovic** [comment]
I think it would. Other possible solutions would be to eliminate any linefeeds during the assertion, or replacing any `\r\n` occurrences with `\n`.

**Comment by pauarge** [comment]
I think we should go down the path of replacing all hardcoded references to `\n` in our code to `PHP_EOL`.

**Comment by acicovic** [comment]
I haven't looked into that yet, but from what I remember I don't think the `\n`s are hardcoded in that string. It may have to do with the file's encoding, but it is an easy fix anyway. I can take this if you want me to work on it.

**Comment by acicovic** [comment]
I started by trying to fix the tests, but they had messy mixed line feed issues, so I went ahead to address the root cause instead of fragile workarounds in tests. This is done in the above PR.
