### ISSUE TITLE
Pre-commit CSS linting: Consider allowing selectors with underscores

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#639]
## Is your feature request related to a problem?
I'm using the  `body.settings_page_parsely` selector (which denotes the plugin's settings page) in CSS, but when trying to commit, the pre-commit process throws a `"Selector should use lowercase and separate words with hyphens"` error and blocks the commit.

## Describe the solution you'd like
Allow selectors with underscores to pass the linting phase so committing is possible.

## Describe alternatives you've considered
In the specific case I can get around this by using an ID and removing the above selector, but this may not always be the case and especially if we plan on manipulating WordPress markup we have no control over.

**Comment by pauarge** [comment]
This is an expected behavior. Our CSS linter is using `@wordpress/stylelint-config`, which matches the standard WordPress expected styles. 

In the specific case of selectors, we shouldn't be using underscores as per the coding standards: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/css/#selectors

**Comment by acicovic** [comment]
What I probably didn't clarify well enough is that `body.settings_page_parsely` is a WP class we have no control over. I do agree that we shouldn't use underscores in our own CSS selectors, and that what I'm describing here is a solution to a potential problem that we aren't facing at the moment. So feel free to close this if you think it is not relevant.

**Comment by pauarge** [comment]
We should do our best to stick to the standards. Changing the linter is easy, but it’s a downhill path from there.
