### ISSUE TITLE
Better docs for after_set_parsely_page

### ISSUE THREAD

**Issue by jtotoole** [Parsely/wp-parsely#64]
We could use a more extended explanation that includes how to set up the callback that needs to be passed when you add the filter

**Comment by GaryJones** [comment]
The filter is called [here](https://github.com/Parsely/wp-parsely/blob/1ad3e6b26ad484343c35bdabbcfc0e29512f2148/wp-parsely.php#L925), but it has no DocBlock.

The readme has [a question](https://github.com/Parsely/wp-parsely/tree/f078868272e41bdac351126b224d276fad1306f5#how-can-i-edit-the-values-passed-to-the-json-ld-metadata) about it, but it could be expanded on (and made to follow WordPress coding standards).

**Comment by mikeyarce** [comment]
Hook was documented in https://github.com/Parsely/wp-parsely/pull/170

**Comment by GaryJones** [comment]
The hook was documented, but more example of its usage could be added to the Readme (I think there's one example, which might need refreshing), and/or the Parse.ly Help docs.
