### ISSUE TITLE
Expose Parse.ly tracker onload event

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#640]
## Is your feature request related to a problem?

The initial building block for advanced integrations is the `window.PARSELY` global object loaded whenever the `p.js` tracking script is inserted on the page. The majority of instructions on our docs page refer to hooking into the `onload` method that the Parse.ly library offers.

With a catch, users can absolutely do that hook right now on wp-parsely. The onload definition must be done before the script is loaded for the snippets to work. This is non-trivial, and a developer would have to reverse-engineer our plugin to insert their code in a specific place on their plugin code.

We must provide a hook within wp-parsely to let users run their JS code to address this issue. This way, we can ensure that it will run before the tracking script is inserted.

## Describe the solution you'd like

We must create a new WordPress action in our `Scripts` class that lets a user define their own `onload` function. If that action is defined, we should insert the developer's code *before* the Parse.ly tracking script is loaded. We should provide the boilerplate for onload and the user would only have to provide the actual function.

Schematically, this is what we should output to the HTML front-end.

```
<script>
    window.PARSELY = window.PARSELY || {
        onload: // code of the JS function extracted from the filter goes here.
    };
</script>

<!-- START Parse.ly Include -->
<!-- ...insert the parsely tracker code here... -->
<!-- END Parse.ly Include -->
```

## Describe alternatives you've considered

Not implementing it and leaving it to the developer properly hooking their calls.

## Additional context

https://www.parsely.com/help/integration/category/tracking

**Comment by GaryJones** [comment]
Needs verifying (completely untested), but I think this can already be done by customers without further changes:

```php
add_action(
	'wp_enqueue_scripts',
	function () {
		wp_add_inline_script(
			'wp_parsely_tracker',
			'window.PARSELY = window.PARSELY || { onload: console.log("Hi!") }',
			'before'
		);
	},
	9
);
```

**Comment by pauarge** [comment]
Yes, this will probably work. However, the key point of the issue is 

>  developer would have to reverse-engineer our plugin to insert their code in a specific place on their plugin code

What I mean by that is that your snippet has `9` priority, which doesn't guarantee that the script will work forever (image there's a change on the plugin). My idea was to add a filter that would be maintained for us in terms of guaranteeing the order of execution.
