### ISSUE TITLE
Consider building production CSS files

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#643]
## Is your feature request related to a problem?
We generate production builds for our JS files but not for our CSS files. I'm not sure if this is by design or just something we haven't done yet.

## Describe the solution you'd like
We should consider if we want to be building our CSS files. On that same path, we could also think of including a CSS pre-processor in our pipeline which could probably do this job itself.

**Comment by pauarge** [comment]
I've been looking into this in the context of your PR. Our setup is ready for supporting CSS files, so we can use webpack to bundle them. My proposal is to create a bundle for the admin page, that contains the admin JS and CSS.

Suppose you are creating a file that contains the styles, say `src/css/demo.css`. Then, we should update our webpack config to:

```
'admin': [
	path.resolve( __dirname, 'src', 'js', 'admin-settings' ),
	path.resolve( __dirname, 'src', 'css', 'demo.css' ),
],
```

This would give us compressed `admin.css` and `admin.js` files, which are the ones we'd include in the front-end.

**Comment by acicovic** [comment]
I see that we're not building `wp-parsely.css` either, and that we include it under `"files"` in `package.json`. This makes me think that:

- We could open a new PR to provide production builds for all CSS files (unless there's a reason not to)
- I could create a bundle for `wp-parsely-admin.css` as part of #633 or in a new PR after merging it

Any preferences?

**Comment by pauarge** [comment]
`wp-parsely.css` basically contains styles for the recommended widget. That widget is not in great shape and we'd have to take a look at it after we finish the Recommended Block. I agree that the CSS file doesn't belong where it is right now, but I'd rather leave it as is until we deal with the recommended widget as a whole.

The ideal course of action from my side would be that you include all the necessary CSS (as you suggest) in `wp-parsely-admin.css` on the same PR you're working on.
