### ISSUE TITLE
Provide support for users to whitelist specific post types

### ISSUE THREAD

**Issue by arhine** [Parsely/wp-parsely#66]
Currently, when implemented, the Parse.ly tracker is set for all post types in the publisher's database. A user has suggested that we allow users to whitelist custom post types. 

As the user noted, "If you have a site with multiple post types, you probably only want analytics on one or two."

**Comment by hbbtstar** [comment]
this functionality is implemented in https://github.com/Parsely/wp-parsely/pull/74- once that gets merged we're good to go here!
