### ISSUE TITLE
Plugin error, perhaps BuddyPress conflict?

### ISSUE THREAD

**Issue by arhine** [Parsely/wp-parsely#693]
A Parse.ly customer has filed the following report:

We are getting the attached error on our website, and when we looked into it it is originating from within the Parse.ly plugin. We think it may have something to do with that plugin’s compativility with Buddypress, but we wanted to get your thoughts on it. Also, for this issue or others like it, is there a way for us to easily disable the plugin, so we can test the same functionality and isolate whether that is the issue?

<img width="532" alt="Screen Shot 2022-02-15 at 8 09 20 PM" src="https://user-images.githubusercontent.com/684746/155332844-9a83f81f-2655-4b15-a6f8-0adbbbe26e4e.png">

**Comment by GaryJones** [comment]
[This `get_permalink()`](https://github.com/Parsely/wp-parsely/blob/168e69711b36203fd8bdd73823856683ce77aaf2/src/class-dashboard-link.php#L35) can return `false` if the post doesn't exist.

The `$post` must be a WP_Post (method type declaration), and is passed from [here](https://github.com/Parsely/wp-parsely/blob/168e69711b36203fd8bdd73823856683ce77aaf2/src/UI/class-admin-bar.php#L71), and contains the value of `$current_object = $GLOBALS['wp_the_query']->get_queried_object();`.

@arhine Can you please find out what URLs they were trying to access when this fatal happened? We don't need the domain - just the path after it.

Also, is this a VIP customer?

**Comment by arhine** [comment]
User says that "It is happening whenever a user tries to access their profile."

So on a path such as /members/xxxxxx

Yes, this is a VIP customer.

**Comment by GaryJones** [comment]
Thanks - the team will need to reproduce this, and apply a fix - I think we have all the information we need at the moment.
