### ISSUE TITLE
Allow users to add "top posts" widgets easily to templates

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/wp-parsely#7]
As an author/admin of a WordPress blog, I'd like to be able to easily add a widget to my blog that shows the top posts so that users can easily see popular content and (hopefully) remain on my site.

I'd be able to configure this widget to limit to a specific time range and style it to my needs.

**Comment by hbbtstar** [comment]
This is proving to be a little hairy to ship with the rec widget- going to get that out the door and have this be a feature of 1.12

**Comment by pauarge** [comment]
We are currently working on an improved, Gutenberg-based widget. Closing this issue as a duplicate.
