### ISSUE TITLE
wpcom_vip_get_term_by is being deprecated.

### ISSUE THREAD

**Issue by pjpak** [Parsely/wp-parsely#70]
https://github.com/Parsely/wp-parsely/blob/75ab9a445208b29033a1a25875f200dd573660a7/wp-parsely.php#L881

**Comment by hbbtstar** [comment]
hi @pjpak! thanks for the heads-up.

I'm trying to figure out what function we should move to and can't seem to find any recommendations or changelogs from WP about what we should use in its place- would you be willing to point me to the changelog or release notes where you found this so I can figure out what we should move to? (or any documentation to that end, if you know of something more specific).

Thanks!

**Comment by pjpak** [comment]
Hi @hbbtstar, 

Here is the VIP notice https://lobby.vip.wordpress.com/2017/08/03/deprecating-vip-helper-functions/

We wound up changing to something like:

return get_term_by($args);

thanks
