### ISSUE TITLE
Write Endpoints documentation and update related documentation

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#702]
This issue is a compilation of a few documentation-related comments by @jblz in #642:

> We should pull out `src/Endpoints/README.md` to separate PR & flesh it out with information about how we build our endpoints.

> We should link to documentation for the related proxy endpoint in `src/blocks/recommendations/README.md` as well as the backend API.

**Comment by acicovic** [comment]
I remember that at some point we removed `src/Endpoints/README.md` because it was empty and we were not aiming for public use of the endpoint.

I guess that this issue could become relevant if we ever decide to promote any endpoints for public use. However, I propose to close this and open a new issue when/if needed. @pauarge, do you agree with closing this?

**Comment by pauarge** [comment]
Yes, I don't foresee endpoints becoming public in the short/mid term.
