### ISSUE TITLE
Consider adding layout/style controls to the Recommendations Block

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#708]
## Background
The [Recommendations Block PR](#642) initially featured two layout styles (`list` and `grid`) for the block. In that PR, it was [decided to remove it](https://github.com/Parsely/wp-parsely/pull/642#discussion_r805980712) in order to make the MVP's first release as simple as possible. Just in case we would want to re-add this, the removal has been implemented in ffefdce.

## Possibility for future enhancements
There would be two different approaches:
1. Make the Block's output as minimal as possible and let users customize it with CSS (current approach)
2. Provide some controls that would influence the Block's appearance such as layouts. However, this could be taken further if desired (for example colors, padding, etc)

Although styling the Block should not be a difficult task for developers, adding appearance controls could be of help to customers that don't have many development resources or want to set up something quickly. We should weigh this to see if it's a direction worth exploring.

**Comment by mehmoodak** [comment]
The main purpose of behind current markup is simplicity so I think keeping it as it is for now is good unless we have some customer feedback based on which we can come up with real scenarios and can configure this better in a way that user likes ..... and when that times come we can create a new ticket.

So are we good to close this ticket?

**Comment by acicovic** [comment]
Re-reading this, maybe this is a better fit for GitHub discussions. Feel free to close this.

Pinging @danielabloch in case she sees merit in noting this for future consideration.
