### ISSUE TITLE
Uncaught TypeError: Return value of Parsely\Parsely::get_author_name() must be of the type string, bool returned

### ISSUE THREAD

**Issue by evantwidwell** [Parsely/wp-parsely#721]
## Describe the bug
A Parse.ly customer reported that they were receiving the following error when scrolling on their site: 

> PHP Fatal error: Uncaught TypeError: Return value of Parsely\Parsely::get_author_name() must be of the type string, bool returned in /srv/htdocs/wp-content/plugins/wp-parsely/src/class-parsely.php:912

I have not been able to reproduce this currently on my end and have asked for more clarification on whether this is on one specific page or on all of their pages

## Expected behavior

We would ideally not be getting a fatal error causing site crashing. I haven't been able to find a page where the author value would be set to a Boolean as the error seems to be reporting however

## Environment

Looks like they're on 3.1.2 based on the tracker configuration. 

## Additional context
We don't get a lot of plugin error reports. I'm happy to ask for any clarification that would be helpful in finding a solution. I have already asked if this is occurring on multiple pages or on one as I am curious if they have a bad author value on one page or if there is something bigger going on here. Thank you for helping investigate.

**Comment by evantwidwell** [comment]
Customer responded that they are experiencing the error on all pages

**Comment by GaryJones** [comment]
https://github.com/Parsely/wp-parsely/blob/3.1.2/src/class-parsely.php#L891-L913 is the function in question for v3.1.2.

Assuming the customer is indeed on 3.1.2, then it would appear that one of the following is returning a boolean:
- `$author->display_name`
- `$author->user_firstname . ' ' . $author->user_lastname`
- `$author->nickname`
- `$author->user_nicename`

`$author` is populated from the `WP_User` class, which has a [`__get()` magic method](https://github.com/WordPress/WordPress/blob/f33f3979cab4429cdba57eff19fde6a2ef957379/wp-includes/class-wp-user.php#L303-L331) to handle the population of the properties.
