### ISSUE TITLE
Automate changelog generation and version bumps

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#731]
## Is your feature request related to a problem?
Currently, in order to make every release we update the changelog and version numbers manually in the code.

## Describe the solution you'd like
This can be automated. @GaryJones has shared with us 2 PRs that we could adapt for our own use:

- https://github.com/Automattic/ad-code-manager/pull/153
- https://github.com/Automattic/ad-code-manager/pull/154

**Comment by acicovic** [comment]
We're aiming to have this for the 3.3.0 release, but if it's not possible we will implement it within the 3.4.0 timeframe.

**Comment by acicovic** [comment]
Related / of interest:
- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
- https://github.com/Automattic/vip-go-mu-plugins/commits/master/.github/workflows/release-changelog.yml

**Comment by GaryJones** [comment]
Note that something didn't go quite right in the ad-code-manager build/release state (not sure what), so the WordPress.org didn't end up with the Changelog section included.

**Comment by acicovic** [comment]
> Note that something didn't go quite right in the ad-code-manager build/release state (not sure what), so the WordPress.org didn't end up with the Changelog section included.

Hm, thanks a lot for letting us know.

**Comment by acicovic** [comment]
This is now implemented in #875. Any further possible enhancements to this will be posted as separate issues.
