### ISSUE TITLE
Fix linting violations in built PHP files

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#744]
## Is your feature request related to a problem?
In certain environments, linting is finding errors within our built PHP files (`build` directory). The issues to fix would be:
- Add a blank line in the end of the file
- Add leading and trailing spaces in arrays

## Describe the solution you'd like
Check our building solution and see if we can set it so our built PHP files can follow the WP Coding Standards or enforce certain formatting rules.

**Comment by GaryJones** [comment]
I think it would be more efficient just to exclude `/build` from the linting / coding standards checks. We don't need coding standards for automatically generated code - it's not something humans will be editing manually.

**Comment by pauarge** [comment]
We are excluding those built files from the affected environments. No other changes are required on the plugin side.
