### ISSUE TITLE
Add documentation example of modifying the Parse.ly canonical url value

### ISSUE THREAD

**Issue by thompsonjoshua** [Parsely/wp-parsely#785]
## Is your feature request related to a problem?
Two customers are producing duplicate content.  This creates downstream issues such as split tracking in the Parse.ly dashboard.  Another downstream effect is that the duplicate content is served up as recommended/related reading.  The primary difference in the duplicate content is that some have the `www` subdomain, whereas other urls are on a naked domain.  Providing the [current documentation](https://www.parse.ly/help/integration/wordpress) has been insufficient.  

## Describe the solution you'd like
I would like to see the [current documentation](https://www.parse.ly/help/integration/wordpress) to include an example where a given url has it's canonical url modified.  For example: 

Here's how to set these two urls to have the same canonical url
1. www.example.com/article-1
2. example.com/article-1
(code follows)

## Describe alternatives you've considered
I think a better solution may be to prevent the creation of the duplicate content in the first place.  However, I'm not sure how the duplicate content was created.  One customer uses WP 5.9.1.  The other uses WP 5.9.3.

## Additional context
I originally requested this example in [another repo](https://github.com/Parsely/web/issues/12679).

**Comment by pauarge** [comment]
Hi Joshua,

We have been looking at this and we don't think it's an issue with the plugin itself. We are using a standard way of fetching the current URL on WordPress, and any changes we do in our plugin side will be confusing and not consistent with the rest of the site. That is, if we handled this duplication on the plugin (for instance, always removing `www`), other parts of the site (and plugins) would not have the same benefits. There are also a lot of edge cases and different configurations that we can't possibly take into account.

That is to say, the problem of duplication has to be solved at a site (WordPress) level, not at the plugin's one. What we can offer is to use the `wp_parsely_permalink` or `wp_parsely_metadata` filters to modify this at a user level.

I am updating our docs to provide suggestions for this.
