### ISSUE TITLE
Add icon to Parse.ly WP plugin

### ISSUE THREAD

**Issue by joshuarrrr** [Parsely/wp-parsely#79]
for better branding and legitimacy
![screenshot from 2018-01-04 13 35 21](https://user-images.githubusercontent.com/1679762/34580897-25e3c354-f154-11e7-988c-93088ab436e9.png)

**Comment by jtotoole** [comment]
the way to add the icon is to drop an image following their naming convention into an `assets` folder as part of the svn deploy https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons

we can do so when deploying 1.13

**Comment by hbbtstar** [comment]
it's actually 1.12, I don';t know why I said 1.13 in slack just now

**Comment by joshuarrrr** [comment]
fixed in svn repo on wordpress.org
