### ISSUE TITLE
Rename "API Key" to "Site ID"

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#799]
## Is your feature request related to a problem?
In different places within the plugin and its documentation, we may refer to the `Site ID` as `API Key`. To avoid confusion, everything should be renamed to `Site ID`. 

## Describe the solution you'd like
Find all occurrences of `API Key` and change them to `Site ID` within the plugin's code and the documentation.

**Comment by acicovic** [comment]
This process is complete for our public documentation.

**Comment by danielabloch** [comment]
> This process is complete for our public documentation.

Does this mean we've updated public documentation to use the term Site ID? 
If so, has this also been updated in the code? In the plugin settings UI?

**Comment by acicovic** [comment]
> Does this mean we've updated public documentation to use the term Site ID?

Correct.

> If so, has this also been updated in the code? In the plugin settings UI?

Plugin settings UI should be good. However, we still use the term API Key internally in various places of the code, and there are a couple of user-facing messages that include this term, although most users will never see those error messages.

As such, this is not 100% complete. The notion of API Key is also used in fragile parts of code that should be handled with care.
