### ISSUE TITLE
Consider restructuring tests folder

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#805]
## Is your feature request related to a problem?
Maybe our `tests` folder structure could use some improvement.

## Describe the solution you'd like
Think of how `test` folder structure should be, or if we should follow any other alternative approach. After this is decided, implement it.

**Comment by GaryJones** [comment]
What's wrong with the current structure? What problem would you be trying to solve?

**Comment by acicovic** [comment]
I don't have a "scientific" answer for that and maybe this is just subjective. For example, some things that seem to jump out to me by looking at this:

- Within the tests directory, We have an `e2e` and `js` directory. Maybe it makes sense to merge those 2.
- Some directory names use lowercase, others title case.
- Is the `specs` subdirectory within the `e2e` directory needed?
- We test the Recommendations Block both in `e2e/specs/blocks/recommendations` and `js/blocks/recommendation/` folders. Maybe we could centralize tests per component in some cases?

Of course, we don't browse in `tests` all day long, and maybe I'm just being picky. But I have the feeling that it could be improved by someone who has a higher-level view of this than me.
