### ISSUE TITLE
switch to config-free tracker snippet

### ISSUE THREAD

**Issue by jtotoole** [Parsely/wp-parsely#82]

**Comment by davisshaver** [comment]
What does this ticket mean?

**Comment by jtotoole** [comment]
Some internal jargon—we've got a new way of serving our JavaScript library that doesn't require the preliminary step of beaconing a separate server that specifies a customer's feature configuration. That's helpful because it decreases the time it takes for our library to load. To implement it for the plugin, we'll be swapping in a different JavaScript snippet in place of the one here:

https://github.com/Parsely/wp-parsely/blob/master/parsely-javascript.php#L42-L59

**Comment by davisshaver** [comment]
Sounds very useful... that could also explain the discrepancy with GA, right? What's the timeline internally on v1.13 for you guys/have these stories been assigned to a sprint?

**Comment by jtotoole** [comment]
yeah it should tighten up differences with tools like GA that load synchronously. we've got the next version of the plugin in development at present, probably looking at shipping in 3-4 weeks

**Comment by joshuarrrr** [comment]
@davisshaver We had to prioritize some code cleanup/linting fixes requested by the WordPress VIP reviewers first that delayed this update. Now that work is winding down, this is the next highest priority.
