### ISSUE TITLE
Consider using GitHub's dependency review action

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#834]
## Is your feature request related to a problem?
We are not using GitHub's [dependency review enforcement action](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement), but perhaps we would want to.

## Describe the solution you'd like
Decide if we would like to implement this and act accordingly.

## Additional context
- https://github.blog/2022-04-06-prevent-introduction-known-vulnerabilities-into-your-code/
- https://github.com/Automattic/vip-go-mu-plugins/pull/3042

**Comment by sjinks** [comment]
Just in case, here is the updated workflow: https://github.com/Automattic/vip-go-mu-plugins/blob/734cab74dba572acb27249d5997f8b47495523ee/.github/workflows/dependency-review.yml
