### ISSUE TITLE
Should schema.org image be withheld if no image available?

### ISSUE THREAD

**Issue by davisshaver** [Parsely/wp-parsely#84]
See proposal in https://github.com/Parsely/wp-parsely/pull/83

Example validation error.

![screen shot 2018-02-23 at 9 59 54 am](https://user-images.githubusercontent.com/1636964/36600459-55bfedc0-1880-11e8-9031-0986c573f996.png)

**Comment by jtotoole** [comment]
closed via https://github.com/Parsely/wp-parsely/pull/83
