### ISSUE TITLE
User finding PHP error in console.

### ISSUE THREAD

**Issue by evantwidwell** [Parsely/wp-parsely#849]
## Describe the bug
A site using the VIP MU plugin reported finding a PHP error in console. It appears to be related to the AMP integration code looking for specific types in metadata. I have not been able to reproduce so far in looking at either regular of AMP pages. 

## Screenshots
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/59800349/167174522-d1aaf8a2-70bc-43c5-8ab9-0d7dccff6584.png">

**Comment by GaryJones** [comment]
Thanks for reporting. Having checked the customer's code, it seems as though they have another callback attached to `amp_post_template_analytics` which is not returning an array or null that the wp-parsely code is expecting (their filter is broken). See our Slack conversation for more info.

I'll leave this open for now until the customer has confirmed, but I suspect this issue can be closed as invalid.

**Comment by pauarge** [comment]
Closing this ticket as this was an issue with the customer's code as Gary points out.
