### ISSUE TITLE
Where could we source the publisher logo?

### ISSUE THREAD

**Issue by davisshaver** [Parsely/wp-parsely#85]
Lack of logo field throws validation error.

![screen shot 2018-02-23 at 10 03 30 am](https://user-images.githubusercontent.com/1636964/36600687-ee7c0080-1880-11e8-80cf-b29dcc8fc8a9.png)

Similar thread in amp-wp. https://github.com/Automattic/amp-wp/issues/552

**Comment by davisshaver** [comment]
See https://github.com/Automattic/amp-wp/issues/975 for AMP WP direction.

**Comment by joshuarrrr** [comment]
@davisshaver closed via https://github.com/Parsely/wp-parsely/commit/2eb7e5daac02fc3b4ed17d75a3d864fbe7690f9e

and available in https://github.com/Parsely/wp-parsely/releases/tag/1.13

We also added a settings field so that users can manually set/override the link
