### ISSUE TITLE
Allow flexibility on metadata date format

### ISSUE THREAD

**Issue by pauarge** [Parsely/wp-parsely#850]
## Is your feature request related to a problem?

We currently render the headline for date page's metadata in a US format (see `class-date-builder.php`). This data is used by the Parse.ly Dashboard to render the page's title.

## Describe the solution you'd like

We'd like to provide more flexibility on how the headline is generated. Specifically, we're targeting the `build_headline` function in `class-date-builder.php`. Instead of using hardcoded formats in `get_the_time` calls, we should use something that takes into account the site's configuration. 

Something like: 

```
get_option('date_format');
get_option('time_format');
```

## Describe alternatives you've considered

Sticking to less flexible date format. The implementation is simpler, but might confuse some non-US users.

## Additional context

See https://github.com/Parsely/wp-parsely/pull/843#discussion_r865807430

**Comment by acicovic** [comment]
For some reason this was not auto-closed, so closing it now.
