### ISSUE TITLE
Display analytics data for published posts within WP admin

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/wp-parsely#9]
Not 100% sure if I wanna do this as the [Parse.ly Analytics Extension](http://www.parsely.com/docs/tools/plugins.html#parse-ly-analytics-extension) currently provides a better experience, but it may still make some sense for a tighter integration into the publishing workflow.

**Comment by pauarge** [comment]
We will be exploring improvements in wp-admin in the future, but closing this issue for now since we need to do some exploration.
