### ISSUE TITLE
Find and remove escaped static strings?

### ISSUE THREAD

**Issue by joshuarrrr** [Parsely/wp-parsely#95]
From the 2018-05-02 WordPress VIP feedback:

> I noticed a number of escaped static strings. Escaping is unnecessary for hardcoded strings, e.g.:
> 
> ```
> echo 'hello'; // this does not need escaping
> echo esc_html( 'hello' ); // not a blocker, but unnecessary
> ```
> 
> It's only when variables are used that escaping is required. Static hardcoded primitives are fine.
> 

I couldn't find any examples of this. @jtotoole or @richeymichael do you see what the referrer is talking about?

**Comment by richeymichael** [comment]
Closest thing I can find: 
https://github.com/Parsely/wp-parsely/blob/master/wp-parsely.php#L640-L642

**Comment by joshuarrrr** [comment]
ah, ok, that makes sense. I think I only looked for `esc_html()` examples.
