### ISSUE TITLE
Use an autoloader for the plugin's files

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#961]
## Is your feature request related to a problem?
Recently, we had to [fix a bug](https://github.com/Parsely/wp-parsely/pull/959) due to a forgotten `require`. @GaryJones, @chriszarate and I agree that moving to an autoloader is a good move. It will help prevent similar issues and allow for cleaner code.

## Describe the solution you'd like
Implement an autoloader solution for the plugin's files.

**Comment by acicovic** [comment]
Reopening this and adding it to our Summer 2024 milestone. This had been implemented in the past, but we had to roll back due to issues.

We maybe can reuse parts of the old PR, but we should conduct more thorough testing to make sure there are no issues.

**Comment by vaurdan** [comment]
I believe this should be either part of #2426, or done before that work, since all the PHP refactoring work will very much benefit from this change. What do you think?

**Comment by acicovic** [comment]
Yes, definitely agree. I prefer this to be isolated work instead of part of #2426, to keep things as atomic as possible.

**Comment by vaurdan** [comment]
Yeah, agree! In that case, I think I will take this one before spending too much time on #2426. I **think** it could be a relatively easy win.

**Comment by acicovic** [comment]
Agreed!
