### ISSUE TITLE
Post Editor (Gutenberg) crash when the Content Helper is hidden and Options is clicked

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#962]
## !!! Temporary workarounds !!!
- When the Content Helper (Parse.ly sidebar) is visible, the Options menu shows up correctly and the Post Editor does not crash. The Content Helper can be shown by clicking on the Parse.ly icon, close to the Options menu icon.
- Rolling back to wp-parsely 3.3.2 fixes the issue. This issue is present in wp-parsely 3.4.0 and 3.4.1. 

## Describe the bug
Clicking the Post Editor's Options menu item (three-dot menu at the top right of the Post Editor) when the Content Helper (Parse.ly sidebar) is hidden results in a crash.

![image](https://user-images.githubusercontent.com/23142906/177732210-723c3d0d-3031-442a-b520-f3074cd2388b.png)

The page goes blank and the following error message is displayed:

![image](https://user-images.githubusercontent.com/23142906/177731354-a98c79a3-e95d-4f55-9224-10b0b5ccb80f.png)

Attempting recovery does not seem to work.

Here is a screenshot of the console error:

![image](https://user-images.githubusercontent.com/23142906/177733242-4ddae69a-0133-4a26-999f-a8daec1b0f6f.png)

## To Reproduce
1. Have wp-pasely 3.4.0 or 3.4.1 installed.
2. Open a Post with the Post Editor.
3. Hide the Parse.ly Content Helper if it is visible.
4. Click the Options icon.
5. The Post Editor will crash.

## Expected behaviour
The Post Editor should continue working, and we should be seeing the Options menu.

## Environment
Reproducible on my local development environment and reported by @gamebits.

**Comment by alecgeatches** [comment]
The crash is coming from the icon registered here:

https://github.com/Parsely/wp-parsely/blob/62bf311710c2e139954f1115ab997d5161595ec7/src/blocks/content-helper/content-helper.tsx#L26-L30

If the icon is replaced with a generic dashicon like this:

```diff
registerPlugin( BLOCK_PLUGIN_ID, {
- 	icon: LeafIcon,
+	icon: 'menu',
	render: renderSidebar,
} );
```

there are no crashes. Something about the `LeafIcon` SVG loading isn't working properly.

The icon that crashes the sidebar is actually the same icon being used in the top bar:

![image](https://user-images.githubusercontent.com/17870752/177761671-bc65038c-cd29-4d71-a594-676908426c6c.png)

This icon changes to the default "menu" icon with the test changes above. So it seems that loading the `LeafIcon` SVG works fine in the menu bar, but the same icon fails in the side bar.

**Comment by alecgeatches** [comment]
I think I've hit the end of my applicable React and type knowledge here, so looking for anyone else's input.

**Comment by acicovic** [comment]
Alec, thanks for your time and work. It is greatly appreciated!

**Comment by ryanwelcher** [comment]
Not sure if this will help but I've had better luck covering SVG files into components with this tool - https://svg2jsx.com/. You can then import it as any you would any other kind of component.

**Comment by acicovic** [comment]
Thanks @ryanwelcher, I know @chriszarate is working on something and we'll see how things go from here.
