### ISSUE TITLE
Content Helper: Add current post information

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#965]
## Is your feature request related to a problem?
The Content Helper doesn't currently include any information about the current post being edited.

## Describe the solution you'd like
Add a panel to the Content Helper that will show certain useful information about the post that is being currently edited. To do that, we should:
- Get the post's published URL.
- Use the Parse.ly API to get information about the post.

From a quick research, here is the information we can currently show about a post using the API:
- https://www.parse.ly/help/api/analytics-endpoint#get-analyticspostdetail
- https://www.parse.ly/help/api/referrers#get-referrerspostdetail
- https://www.parse.ly/help/api/shares#get-sharespostdetail

Some questions to ask ourselves here would be:
- What qualifies as "useful information"?
- Would any of the above information provided by the API be considered as useful?
- What would be some useful information to show that is not currently provided by the API, and can the API be extended to provide it?

**Comment by danielabloch** [comment]
**Describe the solution you'd like**
Add an option to the Content Helper that shows the customer how this post has performed so far, either
- Currently (real-time) or
- In past X time period

How this post has performed so far =
- page views
- engaged time
- % of traffic from each channel (search, social)

**Additional context**
Giving users this context directly while they're publishing helps them decide how to update the post.

[customer research from December 2021](https://parselyproductteam.wordpress.com/2021/12/15/a-look-into-the-pre-publish-and-update-workflows/)
